### ISSUE TITLE
jproxy passing general java objects

### ISSUE THREAD

**Issue by Eothred** [originell/jpype#106]
I have tried to read the documentation but I think I might not be enough of an expert to understand. Basically what I want to do is using in python an interface which defines a function that takes in another java object as input parameter. Looking at your tests it seems that you are only testing that you can pass primitive types (if that is the correct term). May I ask if this is supposed to be possible?

Something along the lines of:
```java
public interface MyInterface {
  public void myFun(AnotherInterface anotherInterface);
}
```
and then in Python:
```python
...
class MyInterface:
  def myFun(self, anotherInterface):
    anotherInterface.anotherFunction()
my_interface=MyInterface()
jpype.JProxy("MyInterface", inst=my_interface)
...
```

I have tried this with a toy setup. I managed fine to set up a proxy defining functions that would get doubles, integers or similar. As soon as I call a function like myFun() above though, the function runs once but then at exit I get a fatal error from Java:
```zsh
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001006a45b7, pid=8915, tid=19215
#
# JRE version: Java(TM) SE Runtime Environment (7.0_67-b01) (build 1.7.0_67-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.65-b04 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [Python+0x555b7]  subtype_dealloc+0x42
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/yngvelevinsen/Downloads/hs_err_pid8915.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
zsh: abort      python -d test_jpype_proxy.py
```

**Comment by yetifrisstlama** [comment]
Hi,

I'm having the same problem here on
 * Linux  ( 2.6.32-504.3.3.el6.x86_64 )
 * java 1.7.0_45
 * Python 2.7.9 :: Anaconda 2.1.0 (64-bit)

I made a small test setup to reproduce the bug in an [ipython notebook](http://nbviewer.ipython.org/url/mbetz.web.cern.ch/mbetz/pyjapc/ReconstructCrash.txt).

Calling the JProxy from Java works fine with primitive types as arguments. 
But as soon as a Java Object is handed over, the JVM crashes **After** the python callback is executed. The Python kernel crashes as well. I attached the error message below.

Any suspicions on what could be going on here?

Cheers YFL.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f96cf92f52d, pid=28676, tid=140285703464704
#
# JRE version: Java(TM) SE Runtime Environment (7.0_45-b18) (build 1.7.0_45-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.45-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpython2.7.so.1.0+0xac52d]  subtype_dealloc+0x10d
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /afs/cern.ch/user/m/mbetz/PY_JAPC/jvmCrash/hs_err_pid28676.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by kutschkem** [comment]
Same problem here with
* python 2.7.9 (64-bit)
* Windows 64-bit
* JDK 1.7.0_67 (64-bit)

I am using javassist to create a proxy of an abstract class, which involves creating a JProxy for the MethodHandler interface.
