### ISSUE TITLE
jpype.isJVMStarted() is 1 after calling jpype.shutdownJVM()

### ISSUE THREAD

**Issue by alibozorgkhan** [originell/jpype#116]
I need to restart the JVM to free up the heap space. But after shutting the JVM down, I can't start it again. I get `Segmentation fault: 11`. I checked the JVM status using `jpype.isJVMStarted()` and it is `1` after shutdown.

**Comment by marscher** [comment]
Sorry, don't know about boilerpipe. It seems like the result of getHTML() is not being garbage collected in JVM. You can trigger garbage collection manually with

     jpype.java.lang.System.gc()

But actually this should not be necessary.

Have you tried increasing the the maximum heap size of the jvm? 

    import jpype
    jpype.startJVM( jpype.getDefaultJVMPath() ), ['-mx512m'] )

**Comment by marscher** [comment]
If your heap space is too small and your methods do not reuse memory, but allocate new one e.g. in every iteration, the garbage collector might not be able to regain the memory fast enough. Increasing heap size will help most probable.

**Comment by alibozorgkhan** [comment]
Thanks for the tips. I tried increasing the heap size and adding garbage collection but no luck.

**Comment by marscher** [comment]
you can monitor garbage collection, if you pass -verbose:gc as jvm 
argument. Maybe that will give us some hints.

**Comment by alibozorgkhan** [comment]
No useful information. I think it's just the way boilerpipe creates instances. You need to create an instance for each page you wanna extract its info: https://github.com/misja/python-boilerpipe/blob/master/src/boilerpipe/extract/__init__.py#L61

So, I think I can't do anything in jpype. Thanks for the help though.
