### ISSUE TITLE
Jpype passing args to Java

### ISSUE THREAD

**Issue by rutvi-zymr** [originell/jpype#117]
I have a java programmer with following line

    service.loadPropertiesForItems(Inbox, new PropertySet(ItemSchema.Subject, ItemSchema.Body));

Program calls classes and methods from external jars.

I want to write equivalent code in python which calls external jars like my java program does.
Using Jpype I implemented the code but it fails on following line

    service.loadPropertiesForItems(inbox, ewsPkg.PropertySet(ewsPkg.ItemSchema.Subject,   ewsPkg.ItemSchema.Body))

Here PropertySet, ItemSchema are classes which I use from external jar.
ItemSchema.Subject and ewsPkg.ItemSchema.Body are class type

Running the code I get following error on line mentioned above -

    service.loadPropertiesForItems(inbox, ewsPkg.PropertySet(ewsPkg.ItemSchema.Subject, ewsPkg.ItemSchema.Body))
    File "C:\Python27\lib\site-packages\jpype\_jclass.py", line 79, in _javaInit
      self.__javaobject__ = self.__class__.__javaclass__.newClassInstance(*args)
    RuntimeError: No matching overloads found. at src/native/common/jp_method.cpp:121

Thanks

**Comment by marscher** [comment]
The error states, that no method signature can be found matching the provided arguments. I assume you have those external jars on jpypes classpath?

which types do the arguments have?
whats the java signature of service.loadPropertiesForItems?

**Comment by rutvi-zymr** [comment]
-> Yes, I have external jars on classpath

jvmPath = jpype.getDefaultJVMPath()
jpype.startJVM(jvmPath, "-ea", "-Djava.class.path=D:\Test\commons-cli-1.2.jar;"
               "D:\Test\EWSJavaAPI_1.2.jar;"
               "D:\Test\jcifs-1.3.17.jar;"
               "D:\Test\commons-codec-1.2.jar;"
               "D:\Test\commons-httpclient-3.1.jar;"
               "D:\Test\commons-logging-1.0.4.jar;"
               "D:\Test\junit-3.8.1.jar;")

-> writing a statement in two parts- 
    PropertySet = ewsPkg.PropertySet(ewsPkg.ItemSchema.Subject, ewsPkg.ItemSchema.Body)
    service.loadPropertiesForItems(inbox, PropertySet)

found that error occurs on the line-
    PropertySet = ewsPkg.PropertySet(ewsPkg.ItemSchema.Subject, ewsPkg.ItemSchema.Body)

for which java equivalent statement is 
    PropertySet propertyset = new PropertySet(ItemSchema.Subject, ItemSchema.Body);

Here, PropertySet and ItemSchema are classes from external jar.
signature of PropertySet is-
    microsoft.exchange.webservices.data.PropertySet.PropertySet(PropertyDefinitionBase... arg0)

-> checking type of arguments with following
    print type(ewsPkg.ItemSchema.Subject)
    print type(ewsPkg.ItemSchema.Body)
    
    prints-
    <class 'jpype._jclass.microsoft.exchange.webservices.data.StringPropertyDefinition'>
    <class 'jpype._jclass.microsoft.exchange.webservices.data.ComplexPropertyDefinition'>
    
Thank you for your help

**Comment by marscher** [comment]
try wrapping subject and body in an array

**Comment by rutvi-zymr** [comment]
As per your suggestion, following code works well.

    ItemSchema = ewsPkg.ItemSchema
    PropertyDefinition = ewsPkg.PropertyDefinition
    Subject = ItemSchema.Subject
    Body = ItemSchema.Body

    args = JArray(PropertyDefinition)([ItemSchema.Subject, Body])
    PropertySet = ewsPkg.PropertySet(args)

Thank you so much.
