### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by baztian** [originell/jpype#119]
Hi,
anyone willing to port jpype to python 3? I know there is the @tcalmant port. But it is not up to date.
I could help out porting the Python part but probably won't be a big help porting the C code ;)
Nice infos can be found here:
http://python3porting.com/
https://docs.python.org/3/howto/pyporting.html

**Comment by tcalmant** [comment]
Hi,
When I started porting the project, I made a very small documentation (in French, sorry :p).
Here are the links, maybe Google translate can help for now. I'll translate them ASAP.

https://github.com/isandlaTech/cohorte-runtime/blob/master/documents/doc-jpype-py3/source/jpype-py.rst
https://github.com/isandlaTech/cohorte-runtime/blob/master/documents/doc-jpype-py3/source/jpype-c.rst
https://github.com/isandlaTech/cohorte-runtime/blob/master/documents/doc-jpype-py3/source/liens.rst

FYI, the most "painful" parts for the conversion are:
* the conversion of string/unicode to bytes/string in Python 3
* the replacement of PyObject by PyCapsule to let Python keep track of our C objects

Finally, the setup.py file of jpype-py3 adds support for Cygwin, if you're interested.

**Comment by marscher** [comment]
@baztian porting the c-part is also the hardest part. I've tried once, but especially the string conversion is really painful.

**Comment by tcalmant** [comment]
Here is a translated version of the C++ part of my previous links:
https://github.com/tcalmant/jpype-py3/wiki/py3_cpp

Another solution could be to update the jpype-py3 fork project, and to merge them once they'll have equivalent features :)

**Comment by baztian** [comment]
Hi @tcalmant, your documentation looks really promising. Maybe it convices @marscher to give it another try on the c/c++ part :)

**Comment by marscher** [comment]
a nice starting point would be to have equal test suites for py2/3, so
progress can be tracked during development.

**Comment by baztian** [comment]
That's definitely something where I can help / what I can do. 



"Martin K. Scherer" <notifications@github.com> schrieb:
>a nice starting point would be to have equal test suites for py2/3, so
>progress can be tracked during development.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/originell/jpype/issues/119#issuecomment-73742639

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by marscher** [comment]
@tcalmant, do you think its reasonable to wrap PyObject/PyEncapsulate in
our own wrapper class for compatibility or might it be enough to define
some "clever" macros?

**Comment by tcalmant** [comment]
Well, PyCapsule has a backport for Python 2.7 and 3.1+, so it could be used directly if you don't target Python 2.6.
BUT, I think that wrapping this kind of class is a better option: the Python C API has proved it is no fully stable on this kind of subject, so having a custom wrapping would simplify the maintainance of the library.

Also, +1 for test suites :)

**Comment by marscher** [comment]
I thought we have already dropped out support for Python 2.6, so we
could use PyCapsulate. A wrapper would also be nice, but it also add
additional overhead.

**Comment by baztian** [comment]
Python 2.6 is still in the travis build matrix

**Comment by baztian** [comment]
OK, tests and python code should now be python 3 compatible. Anyone willing to port the cpp part?

**Comment by rapgro** [comment]
Please merge tcalmant's tests. Current tests do not work because of old print syntax (for Python2 only).

**Comment by baztian** [comment]
What kind of tests do you mean? We have a working testsuite. Please find the tests at https://github.com/originell/jpype/tree/master/test/jpypetest and the results at https://travis-ci.org/originell/jpype.
Print statements in unit tests are generally a bead idea. We don't have print statements in our tests.

**Comment by rapgro** [comment]
I am talking about the parent folder: https://github.com/originell/jpype/tree/master/test
The files there include print statements. You should fix for Python3 usage, as so tcalmant has obviously done. Thanks.

**Comment by rapgro** [comment]
Bytecompiling .py files below /home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4 using /usr/bin/python3.4
*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/buf_leak_test.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/buf_leak_test.py", line 19
    print 'string got deleted'
                             ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/buf_leak_test3.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/buf_leak_test3.py", line 27
    print 'created string', cnt
                         ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/convtest.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/convtest.py", line 31
    print 'Running baseline test : converting a python string->array.array->JArray(JByte). size = ', len(data)/1024.0, 'kb'
                                                                                                  ^
SyntaxError: invalid syntax

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/findjvm.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/findjvm.py", line 20
    print os.path.dirname(os.path.dirname(jvmlib))
           ^
SyntaxError: invalid syntax

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/java_dom.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/java_dom.py", line 55
    print count, "iterations in", t2-t, "seconds"
              ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/java_sax.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/java_sax.py", line 72
    print count, "iterations in", t2-t, "seconds"
              ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/lists_and_maps.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/lists_and_maps.py", line 13
    print arr
            ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/python_dom.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/python_dom.py", line 49
    print count, "iterations in", t2-t, "seconds"
              ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/stub.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/stub.py", line 22
    print s
          ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/test_awt.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/test_awt.py", line 5
    print 'Thread started'
                         ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/test_jarray_fixes.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/test_jarray_fixes.py", line 45
    print 'iteration:', i
                     ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '/home/builder/rpmbuild/BUILDROOT/jpype-0.6.1-1.x86_64/usr/lib64/python3.4/site-packages/jpype/test/testlucene.py'...
  File "/usr/lib64/python3.4/site-packages/jpype/test/testlucene.py", line 8
    raise IOError, "Please provide %s" % path.abspath(lucene_jar)
                 ^
SyntaxError: invalid syntax

**Comment by rapgro** [comment]
https://github.com/originell/jpype/issues/153
