### ISSUE TITLE
Possible (java heap) memory leak

### ISSUE THREAD

**Issue by simon-og** [originell/jpype#121]
I have JPype 0.5.7 on python 2.7.9.
Windows 7, oracle java 1.8.0_31

I see java objects being leaked, so that I can very quickly hit OutOfMemoryErrorPyRaisable

This is enough to reproduce the problem from me :
https://gist.github.com/simon-og/a422cd452a2a12ba9d1f

I can't reproduce the issue on 0.5.4.2 .

If I don't pass the object back into java I don't see the problem (comment out line 6)

Let me know if you need any more information.

**Comment by baztian** [comment]
c2f1ecb51149228f1fc195c2a7855c24eff97cb0 is the first bad commit
    commit c2f1ecb51149228f1fc195c2a7855c24eff97cb0
    Author: marscher <m.scherer@fu-berlin.de>
    Date:   Sat Feb 8 18:44:57 2014 +0100
    
        some global references were cleaned with local reference cleaners and vice versa
    
    :040000 040000 179f2e898ff5367b723f121f44fad5ecfb1db052 8cc1b20d3294023ea485553d49638f79a2ad35cb M	src

JPype1-py3 from tcalmant doesn't fail.

**Comment by baztian** [comment]
@simon-og, thank you for the report and the test for reproducing it. Awesome!
I'm not a C++ guy so I can't fix it. JPype works when reverting the commit mentioned in my former comment. @marscher I didn't want to fully revert your changes. Can you please have a look. I've implemented a unit test case based on simon-og's gist. https://github.com/baztian/jpype/tree/feature/oom-passed-object-cleanup

**Comment by marscher** [comment]
Thank you @baztian for investigating this and @simon-og. I've changed
the global/local thing because the JVM complaint about the wrong method
being called, but this might also be intended.

So I'm fine with reverting the commit completely if it fixes the problem.
