### ISSUE TITLE
"pip install jpype1" from pypi gets error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by CMTaylor** [originell/jpype#126]
Here's the pip log from trying to install JPype from the package registered at pypi:

------------------------------------------------------------
C:\Python27\Scripts\pip-script.py run on 03/04/15 09:27:43
Downloading/unpacking jpype1
  Getting page https://pypi.python.org/simple/jpype1/
  URLs to search for versions for jpype1:
  * https://pypi.python.org/simple/jpype1/
  Analyzing links from page https://pypi.python.org/simple/jpype1/
    Found link https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.4.3.tar.gz#md5=bd77caac0f690c403741ee523b9fbf40 (from https://pypi.python.org/simple/jpype1/), version: 0.5.4.3
    Found link https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.4.4.tar.gz#md5=c403e6e1c7b2eb1d59ce3c1bb16fae31 (from https://pypi.python.org/simple/jpype1/), version: 0.5.4.4
    Found link https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.4.5.tar.gz#md5=9846be5922a07f5234529b83f4dd878a (from https://pypi.python.org/simple/jpype1/), version: 0.5.4.5
    Found link https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.5.1.tar.gz#md5=6cdd011b1d078dd9fe94ff2b8a5cecb9 (from https://pypi.python.org/simple/jpype1/), version: 0.5.5.1
    Found link https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.5.2.tar.gz#md5=e711173a777cc09556b62a881066f74b (from https://pypi.python.org/simple/jpype1/), version: 0.5.5.2
    Found link https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.5.3.tar.gz#md5=b57fe08a1bab234eac1fda543e934501 (from https://pypi.python.org/simple/jpype1/), version: 0.5.5.3
    Found link https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.5.4.tar.gz#md5=3e684090bef734e759c02c304a92a659 (from https://pypi.python.org/simple/jpype1/), version: 0.5.5.4
    Found link https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.5.tar.gz#md5=8ae364ae3a25ba5c4dd5ec628e5c1b25 (from https://pypi.python.org/simple/jpype1/), version: 0.5.5
    Found link https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.6.tar.gz#md5=8fff49dad9d36c5252cace8d2442c404 (from https://pypi.python.org/simple/jpype1/), version: 0.5.6
    Found link https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.7.tar.gz#md5=71333b39aca9fd08b6d0515bfc6c1d62 (from https://pypi.python.org/simple/jpype1/), version: 0.5.7
  Using version 0.5.7 (newest of versions: 0.5.7, 0.5.6, 0.5.5.4, 0.5.5.3, 0.5.5.2, 0.5.5.1, 0.5.5, 0.5.4.5, 0.5.4.4, 0.5.4.3)
  Downloading from URL https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.7.tar.gz#md5=71333b39aca9fd08b6d0515bfc6c1d62 (from https://pypi.python.org/simple/jpype1/)
  Running setup.py (path:c:\users\a0868050\appdata\local\temp\pip_build_a0868050\jpype1\setup.py) egg_info for package jpype1
    running egg_info
    creating pip-egg-info\JPype1.egg-info
    writing requirements to pip-egg-info\JPype1.egg-info\requires.txt
    writing pip-egg-info\JPype1.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\JPype1.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\JPype1.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\JPype1.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info\JPype1.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    no previously-included directories found matching 'test\classes'
    writing manifest file 'pip-egg-info\JPype1.egg-info\SOURCES.txt'
  Source in c:\users\a0868050\appdata\local\temp\pip_build_a0868050\jpype1 has version 0.5.7, which satisfies requirement jpype1
  skipping extra numpy
Installing collected packages: jpype1
  Running setup.py install for jpype1
    Running command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\a0868050\\appdata\\local\\temp\\pip_build_a0868050\\jpype1\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\a0868050\appdata\local\temp\pip-vy0zgi-record\install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\jpype
    copying jpype\JClassUtil.py -> build\lib.win32-2.7\jpype
    copying jpype\nio.py -> build\lib.win32-2.7\jpype
    copying jpype\reflect.py -> build\lib.win32-2.7\jpype
    copying jpype\_core.py -> build\lib.win32-2.7\jpype
    copying jpype\_darwin.py -> build\lib.win32-2.7\jpype
    copying jpype\_gui.py -> build\lib.win32-2.7\jpype
    copying jpype\_jarray.py -> build\lib.win32-2.7\jpype
    copying jpype\_jclass.py -> build\lib.win32-2.7\jpype
    copying jpype\_jcollection.py -> build\lib.win32-2.7\jpype
    copying jpype\_jexception.py -> build\lib.win32-2.7\jpype
    copying jpype\_jobject.py -> build\lib.win32-2.7\jpype
    copying jpype\_jpackage.py -> build\lib.win32-2.7\jpype
    copying jpype\_jproxy.py -> build\lib.win32-2.7\jpype
    copying jpype\_jvmfinder.py -> build\lib.win32-2.7\jpype
    copying jpype\_jwrapper.py -> build\lib.win32-2.7\jpype
    copying jpype\_linux.py -> build\lib.win32-2.7\jpype
    copying jpype\_properties.py -> build\lib.win32-2.7\jpype
    copying jpype\_pykeywords.py -> build\lib.win32-2.7\jpype
    copying jpype\_refdaemon.py -> build\lib.win32-2.7\jpype
    copying jpype\_windows.py -> build\lib.win32-2.7\jpype
    copying jpype\__init__.py -> build\lib.win32-2.7\jpype
    creating build\lib.win32-2.7\jpype\awt
    copying jpype\awt\__init__.py -> build\lib.win32-2.7\jpype\awt
    creating build\lib.win32-2.7\jpype\awt\event
    copying jpype\awt\event\WindowAdapter.py -> build\lib.win32-2.7\jpype\awt\event
    copying jpype\awt\event\__init__.py -> build\lib.win32-2.7\jpype\awt\event
    creating build\lib.win32-2.7\jpypex
    copying jpypex\__init__.py -> build\lib.win32-2.7\jpypex
    creating build\lib.win32-2.7\jpypex\swing
    copying jpypex\swing\AbstractAction.py -> build\lib.win32-2.7\jpypex\swing
    copying jpypex\swing\pyutils.py -> build\lib.win32-2.7\jpypex\swing
    copying jpypex\swing\__init__.py -> build\lib.win32-2.7\jpypex\swing
    running build_ext
    building '_jpype' extension
    c:\users\a0868050\appdata\local\temp\pip_build_a0868050\jpype1\setup.py:145: FeatureNotice: Turned ON Numpy support for fast Java array access
      FeatureNotice)
    error: Unable to find vcvarsall.bat
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\a0868050\\appdata\\local\\temp\\pip_build_a0868050\\jpype1\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\a0868050\appdata\local\temp\pip-vy0zgi-record\install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build\lib.win32-2.7

creating build\lib.win32-2.7\jpype

copying jpype\JClassUtil.py -> build\lib.win32-2.7\jpype

copying jpype\nio.py -> build\lib.win32-2.7\jpype

copying jpype\reflect.py -> build\lib.win32-2.7\jpype

copying jpype\_core.py -> build\lib.win32-2.7\jpype

copying jpype\_darwin.py -> build\lib.win32-2.7\jpype

copying jpype\_gui.py -> build\lib.win32-2.7\jpype

copying jpype\_jarray.py -> build\lib.win32-2.7\jpype

copying jpype\_jclass.py -> build\lib.win32-2.7\jpype

copying jpype\_jcollection.py -> build\lib.win32-2.7\jpype

copying jpype\_jexception.py -> build\lib.win32-2.7\jpype

copying jpype\_jobject.py -> build\lib.win32-2.7\jpype

copying jpype\_jpackage.py -> build\lib.win32-2.7\jpype

copying jpype\_jproxy.py -> build\lib.win32-2.7\jpype

copying jpype\_jvmfinder.py -> build\lib.win32-2.7\jpype

copying jpype\_jwrapper.py -> build\lib.win32-2.7\jpype

copying jpype\_linux.py -> build\lib.win32-2.7\jpype

copying jpype\_properties.py -> build\lib.win32-2.7\jpype

copying jpype\_pykeywords.py -> build\lib.win32-2.7\jpype

copying jpype\_refdaemon.py -> build\lib.win32-2.7\jpype

copying jpype\_windows.py -> build\lib.win32-2.7\jpype

copying jpype\__init__.py -> build\lib.win32-2.7\jpype

creating build\lib.win32-2.7\jpype\awt

copying jpype\awt\__init__.py -> build\lib.win32-2.7\jpype\awt

creating build\lib.win32-2.7\jpype\awt\event

copying jpype\awt\event\WindowAdapter.py -> build\lib.win32-2.7\jpype\awt\event

copying jpype\awt\event\__init__.py -> build\lib.win32-2.7\jpype\awt\event

creating build\lib.win32-2.7\jpypex

copying jpypex\__init__.py -> build\lib.win32-2.7\jpypex

creating build\lib.win32-2.7\jpypex\swing

copying jpypex\swing\AbstractAction.py -> build\lib.win32-2.7\jpypex\swing

copying jpypex\swing\pyutils.py -> build\lib.win32-2.7\jpypex\swing

copying jpypex\swing\__init__.py -> build\lib.win32-2.7\jpypex\swing

running build_ext

building '_jpype' extension

c:\users\a0868050\appdata\local\temp\pip_build_a0868050\jpype1\setup.py:145: FeatureNotice: Turned ON Numpy support for fast Java array access

  FeatureNotice)

error: Unable to find vcvarsall.bat

----------------------------------------
Cleaning up...
  Removing temporary dir c:\users\a0868050\appdata\local\temp\pip_build_a0868050...
Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\a0868050\\appdata\\local\\temp\\pip_build_a0868050\\jpype1\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\a0868050\appdata\local\temp\pip-vy0zgi-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\a0868050\appdata\local\temp\pip_build_a0868050\jpype1
Exception information:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "c:\python27\lib\site-packages\pip\req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "c:\python27\lib\site-packages\pip\req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "c:\python27\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\a0868050\\appdata\\local\\temp\\pip_build_a0868050\\jpype1\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\a0868050\appdata\local\temp\pip-vy0zgi-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\a0868050\appdata\local\temp\pip_build_a0868050\jpype1

**Comment by baztian** [comment]
jpype requires a c/c++ compiler suite as other python modules implemented in c/c++ do as well. Please google around how to compile c extensions for python on windows. If you don't want to go that route check if there are any precompiled jpype versions for windows.
@marscher Are there any automatically built with app veyor? Can we release them from there to pypi?

**Comment by marscher** [comment]
Am 07.03.2015 um 08:02 schrieb baztian:
> jpype requires a c/c++ compiler suite as other python modules
> implemented in c/c++ do as well. Please google around how to compile c
> extensions for python on windows. If you don't want to go that route
> check if there are any precompiled jpype versions for windows.
> @marscher <https://github.com/marscher> Are there any automatically
> built with app veyor? Can we release them from there to pypi?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/originell/jpype/issues/126#issuecomment-77677159>.
>
yes that should be super easy!

**Comment by marscher** [comment]
@CMTaylor install visual studio or another windows c++ compiler (I'm not familiar with win, sorry). We also should have precompiled windows binaries in a few days.

**Comment by CMTaylor** [comment]
I have Visual Studio installed… before I tried the JPype build. It was the missing .bat file that caused the failure (see my issue on GitHub).
Looking forward to Windows and Mac binaries!

Thanks,
Martin
