### ISSUE TITLE
"python setup.py install"  for JPype1.0.5.7 fails with "error: Unable to find vcvarsall.bat"

### ISSUE THREAD

**Issue by CMTaylor** [originell/jpype#134]
I previously raised Issue #126 but it got closed with no resolution. In that thread, marscher said
"@CMTaylor install visual studio or another windows c++ compiler (I'm not familiar with win, sorry). We also should have precompiled windows binaries in a few days."

I DO have a Windows C++ compiler, Visual Studio Pro 2010, and I ran the following in the VS-enabled CMD prompt. It still fails due to this missing file. And as far as I can see there were no precompiled windows binaries ever made available. In fact, the 0.5.7 release predates Issue #126, and there has been no PyPi release since then.

How does ANYONE use JPype1 on Windows?

C:\JPype\JPype1-0.5.7>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to JPype1.egg-info\requires.txt
writing JPype1.egg-info\PKG-INFO
writing top-level names to JPype1.egg-info\top_level.txt
writing dependency_links to JPype1.egg-info\dependency_links.txt
reading manifest file 'JPype1.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
no previously-included directories found matching 'test\classes'
writing manifest file 'JPype1.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
setup.py:145: FeatureNotice: Turned ON Numpy support for fast Java array access
  FeatureNotice)
building '_jpype' extension
error: Unable to find vcvarsall.bat

**Comment by marscher** [comment]
You might wanna consider using the conda binary, which has been there 
for a long time.

https://binstar.org/omnia/jpype1

but this is specific to Anacondas Python distribution.

Maybe this also helps (googling the error)
http://www.megaleecher.net/Fix_error_misssing_vcvarsall

**Comment by baztian** [comment]
As far as I remember there is a .bat file in the Vcc distribution that sets up the paths. There should also be a launcher in your start menu in the vc folder that opens up a windows command prompt with the paths set up correctly for you.

**Comment by CMTaylor** [comment]
Yup. Used that. Couldn’t find the vcvarsall.bat file.

**Comment by marscher** [comment]
Then maybe you should consider fixing your installation. I can not do it
for you - thats why we closed the older issue, since it is not an issue
in Jpype.

**Comment by CMTaylor** [comment]
This website was helpful to get around the "error: Unable to find vcvarsall.bat":
http://stackoverflow.com/questions/2667069/cannot-find-vcvarsall-bat-when-running-a-python-script
In particular, I started the VS10 enabled CMD window and then manually did
SET VS90COMNTOOLS=%VS100COMNTOOLS%
as shown in comment 29 of the above URL.

This got me further through the build process until it failed with:

C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\mt.exe -nologo -manifest build\temp.win32-2.7\Release\native\common\_jpype.pyd.manifest -outputresource:build\lib.win32-2.7\_jpype.pyd;2

build\temp.win32-2.7\Release\native\common\_jpype.pyd.manifest : general error c1010070: Failed to load and parse the manifest. The system cannot find the file specified.
error: command 'mt.exe' failed with exit status 31

The error message is correct in that the file _jpype.pyd.manifest does not exist in the path build\temp.win32-2.7\Release\native\common. Lots of jp_*.obj files exist in this folder, plus:
_jpype.exp
_jpype.lib

What step should have put the  _jpype.pyd.manifest file there and where does it come from?

**Comment by caspervdw** [comment]
The point is that you should use the same compiler with which your python was compiled, otherwise you can get all sorts of errors. You are trying to compile this with VS10 (=10.0=MSC v.1600), while you actually need the C++ compiler from VS08 (=9.0=MSC v.1500) to compile for Python 2.7.

Microsoft has released a very useful package with the right compilers: http://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

I also found the following guide helpful:
http://www.falatic.com/index.php/120/a-guide-to-building-python-2-x-and-3-x-extensions-for-windows
