### ISSUE TITLE
release 0.6

### ISSUE THREAD

**Issue by marscher** [originell/jpype#135]
I've updated the changelog and authors. 

Since bumpversion does not do what I want (automatically change the changelog, git tag and adopt setup.py) I leave this task to the guy, who introduced this buggy tool :+1:

**Comment by baztian** [comment]
I'm glad to help releasing 0.6.

Anyway, I had to modify the changelog layout to make it work with bumpversion as it doesn't work well with newlines we need to produce valid rst files.

Here is what I did to release:

    $ bumpversion minor
    $ git push upstream master --tags

BTW: You are not forced to use bumpversion. You can still do the steps manually. Bumpversion just helps to not forget steps. Of course bumpversion can't magically detect that we need to update setup.py with "Python 3 support" or write meaningful changelogs automatically.
