### ISSUE TITLE
Pyrfa does not clean up properly

### ISSUE THREAD

**Issue by ihateselectingusernames** [originell/jpype#149]
p = pyrfa.Pyrfa()
There is no elegant way to clean up memory occupied by "p".
Killing the process seems to be the only way. "del p" doesn't work.

Please provide a reliable way to clean up this object.

**Comment by baztian** [comment]
How is Pyrfa related to JPype? Is pyrfa a Java library? Please provide some more details.

I don't know about major JPype memory issues. The memory occupied by java classes should be garbage collected by the JVM at some point. If it doesn't please make sure the java library you are using works properly without JPype.

**Comment by ihateselectingusernames** [comment]
I'm sorry - it was meant for some other project
