### ISSUE TITLE
getDefaultJVMPath() error in ubuntu

### ISSUE THREAD

**Issue by lidiaiprou** [originell/jpype#152]
Hi!
I have tried to install JPype but I think I haven't setup correctly the java path or something like this... I am not familiar with java so I need your help. I have read many similar issues but could not manage to solve it myself.

Technical specifications:
Ubuntu 12.04 LTS
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
I think my java_home is '/usr/lib/jvm/java-7-openjdk-amd64' (this folder exists in my computer).

I have just installed JPype-0.5.4.2 using a setup.py edited so that self.javaHome='/usr/lib/jvm/java-7-openjdk-amd64' in setupLinux function. 

It seems it installs correctly but when I call jpype.getDefaultJVMPath() it returns the following:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lmateo/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/jpype/_core.py", line 96, in getDefaultJVMPath
    return _linux.getDefaultJVMPath()
  File "/home/lmateo/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/jpype/_linux.py", line 36, in getDefaultJVMPath
    jvm = _getJVMFromJavaHome()
  File "/home/lmateo/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/jpype/_linux.py", line 55, in _getJVMFromJavaHome
    if os.path.exists(java_home+"/bin/javac") :
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

It seems java_home is None for python... 

I tried to find the path of the JVM myself but I didn't succeed...

startJVM('/usr/lib/jvm/java-7-openjdk-amd64/bin/javac', "-ea")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lmateo/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/jpype/_core.py", line 44, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unable to load DLL [/usr/lib/jvm/java-7-openjdk-amd64/bin/javac], error = /usr/lib/jvm/java-7-openjdk-amd64/bin/javac: cannot dynamically load executable at src/native/common/include/jp_platform_linux.h:45

As you can see... my knowledge of java is very limited! Any help will be welcomed!

Lídia

**Comment by marscher** [comment]
``` update-alternatives --config java``` should fix your java installation. BTW: JPype-0.5.4.2 is a very old version and you should consider upgrading, since lots of bugs has been fixed

**Comment by lidiaiprou** [comment]
Thank you for your answer!
The command ```update-alternatives --config java``` returns the following:
```{}
There is only one alternative in link group java (providing /usr/bin/java): /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
Nothing to configure.
``` 
Therefore, I assume that JAVA_HOME should be /usr/lib/jvm/java-7-openjdk-amd64. Am I right?

Following your advice, I downloaded the latest Jpype version I found and tried to install it without modifying the setup.py file. It seems everything is Ok... the last lines of the installation process are: 
```
Installed /home/lmateo/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/JPype1-0.6.1-py2.7-linux-x86_64.egg
Processing dependencies for JPype1==0.6.1
Finished processing dependencies for JPype1==0.6.1
```
However, when I try to run the "hello world" example from the documentation, I get the same error as before... It fails when starting JVM, probably because it gets a None value when tries to get JAVA_HOME or something like that... The exact error message is this one:
```
Traceback (most recent call last):
  File "/aloy/home/lmateo/workspace/TCT4U/PathwayCommons/HelloWorld_jpype.py", line 2, in <module>
    startJVM(getDefaultJVMPath(), "-ea")
  File "/home/lmateo/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/jpype/_core.py", line 96, in getDefaultJVMPath
    return _linux.getDefaultJVMPath()
  File "/home/lmateo/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/jpype/_linux.py", line 36, in getDefaultJVMPath
    jvm = _getJVMFromJavaHome()
  File "/home/lmateo/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/jpype/_linux.py", line 55, in _getJVMFromJavaHome
    if os.path.exists(java_home+"/bin/javac") :
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
Any idea?? 

Thank you in advance

**Comment by lidiaiprou** [comment]
It works!!! 
Thank you so much :-)
I was setting my java home at /usr/lib/jvm/java-7-openjdk-amd64/ in stead of /usr/lib/jvm/java-7-openjdk-amd64/jre/
I know it might seem a silly mistake for must of you... but now I won't forget it!! 

There's still something strange... it works if I run it in the terminal but it doesn't if I execute it in Eclipse console... I will have to learn how bash variables are loaded there... but this is another topic!

**Comment by marscher** [comment]
You're welcome! To make this permanent in your $HOME/.bashrc file like I 
said before.
