### ISSUE TITLE
Problem with UCS2 vs UCS4

### ISSUE THREAD

**Issue by nvitucci** [originell/jpype#158]
When I install JPype1 from *pip* and try to import it in Python, I get the following error:

```
import jpype

...
ImportError: /usr/lib64/python2.7/site-packages/JPype1-0.6.1-py2.7-linux-x86_64.egg/_jpype.so: undefined symbol: PyUnicodeUCS2_FromObject
```

My Python installation uses UCS4 as ```sys.maxunicode``` > 65535 (see [here](http://effbot.org/pyfaq/when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2.htm)).

Any way to compile JPype to support UCS4 as well?

**Comment by marscher** [comment]
So if you've compiled jpype against your Python installation, it should use the same amount of bytes for unicode as Python? I do not believe that this is hardcoded in JPype.

Are you really sure pip uses the same Python (headers)?
