### ISSUE TITLE
[Mac OS X] To open "this Java application" you need to install the legacy Java SE 6 runtime.

### ISSUE THREAD

**Issue by e9t** [originell/jpype#160]
[Some users of KoNLPy reported](https://github.com/konlpy/konlpy/issues/76) that upon invoking JPype on a Mac, we get the following error message:

```
No Java runtime present, requesting install.
```

and Python crashes with the following popup:

<img width="532" alt="81662794-543a-11e5-96f5-4dcfcc9f3fc1" src="https://cloud.githubusercontent.com/assets/1205890/10711777/a0552224-7ac1-11e5-9be1-fdba71080f98.png">

I found that [the same issue was reported for rJava](https://github.com/s-u/rJava/issues/37), and they say [this is an official Java 1.8 bug](https://github.com/s-u/rJava/issues/37#issuecomment-67557805).

There seem to be two ways to work around this problem:
1. For the user: [Install Java 1.6](https://support.apple.com/kb/DL1572?locale=en_US)
   [[discussion]](https://github.com/s-u/rJava/issues/37#issuecomment-67557805)
2. For jpype: Call `libjli.dylib` instead of `libjvm.dylib`
   [[example]](https://github.com/s-u/rJava/commit/f8ea2ea9215c890597e40be889d672010cc16b10)
   - `libjvm.dylib`: '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/server/libjvm.dylib'
   - `libjli.dylib:` '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jli/libjli.dylib'

I've tried the latter option for KoNLPy and the crashing went away, but my pre-existing code returned errors like the following:

```
TypeError: Package kr.lucypark.kkma.KkmaInterface is not Callable
```

**Comment by marscher** [comment]
I do not think that we can handle this issue on our side. If there would exist a functional workaround, I'd be happy to accept it.

**Comment by rdllopes** [comment]
Hi, all. I think I am little lost. I didn't get it how @e9t  managed to work around the issue. jpype currently tries to find libjvm.so what it would not happen in mac os X as is. I created symbolic link libjvm.so pointing to libjvm.dylib. However, the native library (_jpype.cpython-35m-darwin.so) 
expects the static library and it refuses to proceed.  @e9t, could you clarify your work around, please.

**Comment by justussc** [comment]
hi @rdllopes, 

you can just start your jvm with `jpype.startJVM('/path/to/libjli.dylib')`  (inserting the correct path) assuming that you are using the latest jpype version from git.
i never submitted a pull request for changing the `_libfile` in `jpype._darwin.DarwinJVMFinder` to libjli.dylib because i am not aware of the implications. but one has to use that file, as the jni methods are in this 'java legacy interface' library on mac os. while on all other platforms i've used they are in the normal libjvm.

**Comment by marscher** [comment]
If the LinuxJVMFinder is used then sys.platform does not evaluate to "darwin" anymore?!
https://github.com/originell/jpype/blob/master/jpype/_core.py#L105

**Comment by justussc** [comment]
that is indeed is suspicious that he said it was searching for libjvm.so.

but even the DarwinJVMFinder does not work for the jvms i tried. one would have to change https://github.com/originell/jpype/blob/master/jpype/_darwin.py#L35 to `self._libfile = "libjli.dylib"`

**Comment by marscher** [comment]
Okay, I will just change it.

**Comment by andybrucenet** [comment]
Platform: OSX Catalina
```
$ sw_vers -productVersion
10.15.4

$ java -version
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
```

Problem: 
```
 /Applications/GanttProject.app/Contents/MacOS/JavaAppLauncher
2020-03-26 11:39:33.270 JavaAppLauncher[16987:304952] NSString *findJavaDylib(NSString *, _Bool, _Bool, _Bool, _Bool) Searching for a JRE.
2020-03-26 11:39:33.271 JavaAppLauncher[16987:304952] NSString *findJREDylib(int, _Bool, _Bool) JRE search exception: 'launch path not accessible'
2020-03-26 11:39:33.340 JavaAppLauncher[16987:304952] int launch(char *, int, char **) Launchpath: /Library/Java/JavaVirtualMachines/openjdk-14.jdk/Contents/Home/lib/jli/libjli.dylib
2020-03-26 11:39:33.343 JavaAppLauncher[16987:304952] int launch(char *, int, char **) Error launching JVM Runtime ((null)) Relative Path: '/Library/Java/JavaVirtualMachines/openjdk-14.jdk/Contents/Home' (dylib: /Library/Java/JavaVirtualMachines/openjdk-14.jdk/Contents/Home/lib/jli/libjli.dylib)
  error: Unable to load Java Runtime Environment.
```

Solution:
```
sudo ln -fs /Library/Java/JavaVirtualMachines/openjdk-14.jdk/Contents/Home/lib \
  /Library/Java/JavaVirtualMachines/openjdk-14.jdk/Contents/Home/lib/jli
```

Done.

**Comment by Thrameos** [comment]
If you have a fix to the JVMFinder to locate the correct shared library it would be great.  Unfortunately I don't have access to a Mac.

**Comment by andybrucenet** [comment]
Hey @Thrameos there are some warnings - they don't block anything so no worries.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.itextpdf.text.pdf.MappedRandomAccessFile$1 (file:/Applications/GanttProject.app/Contents/Java/plugins-2.8.10/org.ganttproject.impex.htmlpdf/lib/itextpdf-5.3.1.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.itextpdf.text.pdf.MappedRandomAccessFile$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Don't think this is Mac issue. Maybe from me using using latest Java?
Just FYI...

**Comment by Thrameos** [comment]
I have seen that on a number of projects including maven.   I believe this this is an issue with the jar org.ganttproject.impex.htmlpdf.   I don't believe it is related to JPype directly.   I think that some libraries are using reflection to access a private field which is now being deprecated.   We do not currently make access to DirectBuffer.cleaner.
