### ISSUE TITLE
crash python with help(jpype)

### ISSUE THREAD

**Issue by RaminFP** [originell/jpype#171]
```python
notic : python version 2.7.10 crash
>>>import jpype
>>>help(jpype)
```

![crashed](http://s7.picofile.com/file/8233445168/12.PNG)

debug informaion;

>>> import jpype
ModLoad: 10000000 1004f000   C:\Python27\lib\site-packages\jpype1-0.6.1-py2.7-win32.egg\_jpype.pyd
ModLoad: 6f700000 6f78e000   C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9158_none_5091b51ebcb97cdc\MSVCP90.dll
>>> help(jpype)
(135c.1cc4): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=00000000 ebx=0257d302 ecx=00000000 edx=40000060 esi=0028e9bc edi=0028e9dc
eip=10006f91 esp=0028e8ac ebp=0028e954 iopl=0         nv up ei pl nz ac po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010212
*** WARNING: Unable to verify checksum for C:\Python27\lib\site-packages\jpype1-0.6.1-py2.7-win32.egg\_jpype.pyd
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Python27\lib\site-packages\jpype1-0.6.1-py2.7-win32.egg\_jpype.pyd -
_jpype+0x6f91:
10006f91 83790400        cmp     dword ptr [ecx+4],0  ds:002b:00000004=????????
0:000> r
eax=00000000 ebx=0257d302 ecx=00000000 edx=40000060 esi=0028e9bc edi=0028e9dc
eip=10006f91 esp=0028e8ac ebp=0028e954 iopl=0         nv up ei pl nz ac po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010212
_jpype+0x6f91:
10006f91 83790400        cmp     dword ptr [ecx+4],0  ds:002b:00000004=????????
0:000> db esi
0028e9bc  a0 5a 55 02 6a 61 76 61-2e 5f 5f 67 65 74 5f 5f  .ZU.java.__get__
0028e9cc  00 ea 28 00 0c 00 00 00-0f 00 00 00 82 4e 0b 1e  ..(..........N..
0028e9dc  4c 6a 61 76 61 2f 5f 5f-67 65 74 5f 5f 3b 00 00  Ljava/__get__;..
0028e9ec  0e 00 00 00 0f 00 00 00-0a 00 00 00 6c 14 03 10  ............l...
0028e9fc  50 2d 4f 02 60 cd 6a 02-30 20 33 02 b6 8a a7 d7  P-O.`.j.0 3.....
0028ea0c  50 7a 58 02 16 00 00 00-1f 00 00 00 00 ae 5d 02  PzX...........].
0028ea1c  0b fb 08 1e 50 7a 58 02-20 26 56 02 b6 8a a7 d7  ....PzX. &V.....
0028ea2c  5c 95 60 02 a8 e9 28 00-70 ff 28 00 11 f5 02 10  \.`...(.p.(.....
0:000> k
ChildEBP RetAddr
WARNING: Stack unwind information not available. Following frames may be wrong.
0028e954 61766100 _jpype+0x6f91
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Windows\SysWOW64\python27.dll -
0028ea18 1e08fb0b 0x61766100
0028ea40 1e0aaed7 python27!PyDict_GetItem+0x9b
0028ea58 1e0edcc0 python27!PyCFunction_Call+0x47
0028ea80 1e0efa6f python27!PyEval_GetGlobals+0x820
0028ea84 1e0f012a python27!PyEval_EvalFrameEx+0x1cdf
0028eadc 1e09dac5 python27!PyEval_EvalFrameEx+0x239a
0028eaf4 1e0f1100 python27!PyFrame_New+0x75
0028eb28 1e09ebca python27!PyEval_EvalCodeEx+0x690
0028eb74 1e07cdec python27!PyFunction_SetClosure+0x86a
0028eb8c 1e088a17 python27!PyObject_Call+0x4c
0028ec20 77dbba01 python27!PyMethod_New+0x757
0028ecb8 77dbb93b ntdll!RtlpReAllocateHeapInternal+0xa1
0028ed24 1e07cdec ntdll!RtlReAllocateHeap+0x2b
0028ed44 1e0c2a5c python27!PyObject_Call+0x4c
0028ed58 1e0c4edd python27!PyObject_LookupSpecial+0xac
0028ed64 1e0ac23d python27!PyType_Ready+0x201d
0028ed70 1e107ebc python27!PyObject_GetAttr+0x3d
0028ed94 1e1079d5 python27!PyModule_AddStringConstant+0x9c
00000000 00000000 python27!Py_InitModule4+0x645
0:000> !analyze -v -nodb
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

FAULTING_IP:
_jpype+6f91
10006f91 83790400        cmp     dword ptr [ecx+4],0

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 10006f91 (_jpype+0x00006f91)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 00000004
Attempt to read from address 00000004

FAULTING_THREAD:  00001cc4

PROCESS_NAME:  python.exe

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_PARAMETER1:  00000000

EXCEPTION_PARAMETER2:  00000004

READ_ADDRESS:  00000004

FOLLOWUP_IP:
_jpype+6f91
10006f91 83790400        cmp     dword ptr [ecx+4],0

NTGLOBALFLAG:  70

APPLICATION_VERIFIER_FLAGS:  0

BUGCHECK_STR:  APPLICATION_FAULT_NULL_CLASS_PTR_DEREFERENCE_NULL_POINTER_READ_INVALID_POINTER_READ

PRIMARY_PROBLEM_CLASS:  NULL_CLASS_PTR_DEREFERENCE

DEFAULT_BUCKET_ID:  NULL_CLASS_PTR_DEREFERENCE

IP_ON_HEAP:  61766100
The fault address in not in any loaded module, please check your build's rebase
log at <releasedir>\bin\build_logs\timebuild\ntrebase.log for module which may
contain the address if it were loaded.

IP_IN_FREE_BLOCK: 61766100

FRAME_ONE_INVALID: 1

LAST_CONTROL_TRANSFER:  from 61766100 to 10006f91

STACK_TEXT:
WARNING: Stack unwind information not available. Following frames may be wrong.
0028e954 61766100 675f5f2e 5f5f7465 00000000 _jpype+0x6f91
0028ea18 1e08fb0b 02587a50 02562620 d7a78ab6 0x61766100
0028ea40 1e0aaed7 00000000 025a47d0 02585d28 python27!PyDict_GetItem+0x9b
0028ea58 1e0edcc0 02585d28 025a47d0 00000000 python27!PyCFunction_Call+0x47
0028ea80 1e0efa6f 1e0f012a 0028eadc 0253b020 python27!PyEval_GetGlobals+0x820
0028ea84 1e0f012a 0028eadc 0253b020 0000a384 python27!PyEval_EvalFrameEx+0x1cdf
0028eadc 1e09dac5 ffffffff ffffffff 00000000 python27!PyEval_EvalFrameEx+0x239a
0028eaf4 1e0f1100 026b1760 00000000 0258a730 python27!PyFrame_New+0x75
0028eb28 1e09ebca 0253b020 026b1760 00000000 python27!PyEval_EvalCodeEx+0x690
0028eb74 1e07cdec 0258a730 026bbc10 00000000 python27!PyFunction_SetClosure+0x86a
0028eb8c 1e088a17 0258a730 026bbc10 00000000 python27!PyObject_Call+0x4c
0028ec20 77dbba01 026ed550 00000040 026ed550 python27!PyMethod_New+0x757
0028ecb8 77dbb93b 026ed550 026ed548 024f0000 ntdll!RtlpReAllocateHeapInternal+0xa1
0028ed24 1e07cdec 025853a0 025a4690 1e0bc4a4 ntdll!RtlReAllocateHeap+0x2b
0028ed44 1e0c2a5c 025853a0 025bf810 025bf810 python27!PyObject_Call+0x4c
0028ed58 1e0c4edd 1e1212bc 02331a00 1e0ac23d python27!PyObject_LookupSpecial+0xac
0028ed64 1e0ac23d 0256259c 00000001 1e107ebc python27!PyType_Ready+0x201d
0028ed70 1e107ebc 0028edcc 0028edc8 00000000 python27!PyObject_GetAttr+0x3d
0028ed94 1e1079d5 0028edcc 0028edc8 00000029 python27!PyModule_AddStringConstant+0x9c
00000000 00000000 00000000 00000000 00000000 python27!Py_InitModule4+0x645

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  _jpype+6f91

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: _jpype

DEBUG_FLR_IMAGE_TIMESTAMP:  56987425

STACK_COMMAND:  ~0s ; kb

BUCKET_ID:  APPLICATION_FAULT_NULL_CLASS_PTR_DEREFERENCE_NULL_POINTER_READ_INVALID_POINTER_READ__jpype+6f91

IMAGE_NAME:  C:\Python27\lib\site-packages\jpype1-0.6.1-py2.7-win32.egg\_jpype.pyd

FAILURE_BUCKET_ID:  NULL_CLASS_PTR_DEREFERENCE_c0000005_C:_Python27_lib_site-packages_jpype1-0.6.1-py2.7-win32.egg__jpype.pyd!Unknown

Followup: MachineOwner
---------

0:000>

**Comment by danielepantaleone** [comment]
I'm having the same problem with Windows 8 and Python 3.4.3. Using JPype 0.6.1 and Oracle JRE 8.

**Comment by marscher** [comment]
it also crashes on linux. Seems like the memory of the module docstring points to nirvana

**Comment by danielepantaleone** [comment]
I'm having the same problem with Windows 8 using JPype 0.6.1 and Oracle JRE 8:

```
>>> import jpype
>>> jpype.startJVM("C:\\Users\\Daniele\\workspace\\eddy\\resources\\jre\\bin\\cl
ient\\jvm.dll")
```

which results in:

> Process finished with exit code -1073741819 (0xC0000005)

**Comment by marscher** [comment]
the help command tries to access the JVM before it has been intialized. So if you start the jvm before, you should be fine.

``` 
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff60532e0 in JPJavaEnv::GetEnv (this=0x0, env=0x7fffffffb368) at native/common/jp_javaenv.cpp:247
247             if (jvm == NULL)
```

**Comment by marscher** [comment]
@danielepantaleone are using 32bit jvm with 32bit python? The bit width of these two components have to match. There is no easy way to catch this error.

**Comment by marscher** [comment]
relevant stack frames are:
```
#0  0x00007ffff60532e0 in JPJavaEnv::GetEnv (this=0x0, env=0x7fffffffb368) at native/common/jp_javaenv.cpp:247
#1  0x00007ffff6051d55 in JPJavaEnv::getJNIEnv (this=0x0) at native/common/jp_javaenv.cpp:51
#2  0x00007ffff606383f in JPJavaEnv::FindClass (this=0x0, a0=0xa5a028 "Ljava/__get__;") at native/common/jp_javaenv_autogen.cpp:1456
#3  0x00007ffff6076dbe in JPTypeManager::findClass (name=...) at native/common/jp_typemanager.cpp:80
#4  0x00007ffff60d7515 in JPypeJavaClass::findClass (obj=0x0, args=0x7fffe8e8fb10) at native/python/jpype_javaclass.cpp:79
#5  0x00007ffff7aefe15 in call_function (oparg=<optimized out>, pp_stack=0x7fffffffb638) at Python/ceval.c:4350
#6  PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:298
```

**Comment by danielepantaleone** [comment]
Yes, I'm using 32 bit JVM with 32 bit python. The original path is: C:\Program Files (x86)\Java\jre1.8.0_71, I just moved it in my project folder because I need to distribute it.

**Comment by marscher** [comment]
So it crashes directly upon starting the JVM? Are you able attach a debugger?

**Comment by danielepantaleone** [comment]
Do you know any debugger I could use? I'm not very familiar with windows, I just use it for compiling/freezing applications. I usually use Valgrind but it doesn't work on Windows.

**Comment by marscher** [comment]
Me neither, I guess you can use Windbg. Dunno if one can get it for free.
https://msdn.microsoft.com/en-us/windows/hardware/hh852365.aspx
