### ISSUE TITLE
Failed with JAR

### ISSUE THREAD

**Issue by arita291** [originell/jpype#173]
Hi,
I tried to load 3rd party jar like this:

```
import jpype as jp
classpath = "E:/lib/java/pdfbox-1.8.11.jar"
jp.startJVM(jp.getDefaultJVMPath(),"-ea", "-DJava.class.path=%s" % classpath)
pd = jp.JPackage("org").apache.pdfbox.pdmodel.PDDocument
document = pd.load("TheTibetansPart1.pdf")

jp.java.lang.System.out.println("Hello World "+jp.JString(document.getNumberOfPages()))
jp.shutdownJVM()

```

I got this message:
  File "python-3.4.4.amd64\lib\site-packages\jpype\_jpackage.py", line 53, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))

1) How can I check if the JAR is well loaded ? (is it a problem of folder path ???)

Kind regards

**Comment by justussc** [comment]
i think this might is just be a problem with your classpath specification. try `-Djava.class.path=%s` instead of `-DJava.class.path=` (note the small 'j' in java). at least on linux these properties are case sensitive.

to check your classloaders classpath you could do something like:

    systemclassloader = jpype.java.lang.ClassLoader.getSystemClassLoader()
    for x in systemclassloader.getURLs():
        print(x)

**Comment by arita291** [comment]
Thank you, am trying this.


On 23 Feb 2016, at 07:52, justussc <notifications@github.com> wrote:

i think this might is just be a problem with your classpath specification. try -Djava.class.path=%s instead of -DJava.class.path= (note the small 'j' in java). at least on linux these properties are case sensitive.

to check your classloaders classpath you could do something like:

systemclassloader = jpype.java.lang.ClassLoader.getSystemClassLoader()
for x in systemclassloader.getURLs():
    print(x)
―

**Comment by marscher** [comment]
jpype-py3/issues/18
