### ISSUE TITLE
scala Lambda function

### ISSUE THREAD

**Issue by ghost** [originell/jpype#179]
Hi,
Is it possible to use Lambda function when calling a scala class in Jpype ?
wrdCnt is a class imported in Python.
Is this syntax possible in Python ?

ntWrd = wrdCnt.map{case (word, count) => (count, word)}

Thanks, regards

**Comment by marscher** [comment]
I dont think so, this is Scala syntax, right? On Pythons side we are restricted to use Pythons grammar. You could wrap it in a normal function, which seems a bit odd.
