### ISSUE TITLE
startJVM is not defined

### ISSUE THREAD

**Issue by PReeeT** [originell/jpype#183]
I am using Ubuntu 14.10, GCC and Python 2.7. I have installed Oracle SDK 1.8. 
When I execute startJVM(getDefaultJVMPath, "-ea")
It produces 
NameError: name 'startJVM' is not defined. 

Could you please help me understand where I am going wrong.

**Comment by marscher** [comment]
maybe startJVM is not defined in your namespace?

**Comment by marscher** [comment]
by the way you have to invoke getDefaultJVMPath, it is also a function (like the name suggests)
