### ISSUE TITLE
jpype fail to find Java class

### ISSUE THREAD

**Issue by PReeeT** [originell/jpype#184]
I have a sample python program to call a Java class
```
import jpype
import os
jpype.startJVM(getDefaultJVMPath(), "-ea", "-Djava.class.path=%s"%os.path.abspath("."))
A = jpype.JClass("A")
a = A()
print a.sayHi()
jpype.shutdownJVM()
```
Java class:
```
class A
{
    public A()
    {
        super();
    }
    public String sayHi()
    {
        return("Hello");
    }
}
```
The python file and java class are in the same directory. When I execute the python code it produces the following error. 
java.lang.RuntimeException: Class A not found

Could you please help me solve this.

**Comment by marscher** [comment]
compile your java code

**Comment by PReeeT** [comment]
I have already complied it. As I have mentioned Java class and python code are in the same folder. By that I mean A.class. 
Please do not close the issue with out hearing out the exact problem.

**Comment by songxiaowei112** [comment]
Did you solve this problem?

**Comment by marscher** [comment]
https://jpype.readthedocs.io/en/latest/install.html#known-bugs-limitations (about the default package limitation)
