### ISSUE TITLE
Can't import jpype module

### ISSUE THREAD

**Issue by sgess** [originell/jpype#189]
Environment:

$ python --version
Python 3.5.2 :: Anaconda 4.2.0 (64-bit)
$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Error when I try to import:

In [1]: import jpype
Traceback (most recent call last):

  File "<ipython-input-1-e9978938630b>", line 1, in <module>
    import jpype

  File "/home/sgess/anaconda3/lib/python3.5/site-packages/JPype1-0.6.1-py3.5-linux-x86_64.egg/jpype/__init__.py", line 17, in <module>
    from ._jpackage import *

  File "/home/sgess/anaconda3/lib/python3.5/site-packages/JPype1-0.6.1-py3.5-linux-x86_64.egg/jpype/_jpackage.py", line 18, in <module>
    import _jpype

ImportError: /home/sgess/anaconda3/lib/python3.5/site-packages/JPype1-0.6.1-py3.5-linux-x86_64.egg/_jpype.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

**Comment by marscher** [comment]
looks like a problem with your c++ standard library? Did you install a binary version or from source?

**Comment by sgess** [comment]
Hi Martin-

First, I tried with the version included in Anaconda. I am not sure if this is a binary or from source. Does Anaconda compile when it installs itself?

That didn’t work, so I removed the jpype package and followed the instructions here:

http://jpype.readthedocs.io/en/latest/install.html <http://jpype.readthedocs.io/en/latest/install.html>

and that also didn’t work.

Thanks for your quick response!

Best
Spencer

**Comment by cstich** [comment]
I got the same error message as @sgess. As there seems to be some mix up with the GCC and anaconda I tried building an anaconda package. That also somewhat works, and I can now import `jpype` in python successfully, however I get the following error message when I try to import `jpypex`.
```
Program received signal SIGSEGV, Segmentation fault.
JPJavaEnv::GetEnv (this=0x0, env=0x7fffffff9880) at native/common/jp_javaenv.cpp:247
247	native/common/jp_javaenv.cpp: No such file or directory.
```

**Comment by marscher** [comment]
you can now install from conda-forge like this:

conda install -c conda-forge jypep1

We should update the documentation accordingly.

**Comment by cstich** [comment]
Thanks. The package installs fine that way.
However, I still get the same seg fault though when I try to import `jpypex`. I don't know how relevant that is, but maybe you want to check that out.

**Comment by marscher** [comment]
Actually I don't ever used this package. I don't even know if it is 
(unit)-tested.

**Comment by marscher** [comment]
@cstich it is used to access javax/swing. So you have to import jpype before and start a jvm to access it.

     python -c "import jpype; jpype.startJVM(jpype.get_default_jvm_path());import jpypex"
works fine

**Comment by marscher** [comment]
@sgess please stick to the pre-compiled version, I can not give support to set up sane development environments.

**Comment by sgess** [comment]
I tried your solution and it works. Thanks!

**Comment by beniroquai** [comment]
Great! It works! :)
