### ISSUE TITLE
pip install on windows fails

### ISSUE THREAD

**Issue by Sahasrara** [originell/jpype#194]
I get:
pip install JPype1

error: Unable to find vcvarsall.bat

**Comment by marscher** [comment]
If you really want to compile on Windows, you need to install Visual C++ for Python etc. I'm not giving support for that. Installing with conda is much easier. (Have a look at the documentation)

**Comment by Sahasrara** [comment]
Ok i'll check out Conda.  can you point me to the documentation you mentioned on how to install JPype with Conda?

**Comment by marscher** [comment]
On 21.12.2016 19:46, Eric Fulton wrote:
> Ok i'll check out Conda. can you point me to the documentation you
> mentioned on how to install JPype with Conda?
It is not yet on readthedocs, but you can find it here:

https://github.com/originell/jpype/blob/master/doc/install.rst

**Comment by Sahasrara** [comment]
thank you!
