### ISSUE TITLE
Unable to install Jpype with pip

### ISSUE THREAD

**Issue by njchandu** [originell/jpype#206]
How can I install Jpype with pip command instead cloning the repo and executing python setup.py install?

**Comment by marscher** [comment]
pip install jpype1

**Comment by njchandu** [comment]
I get this error while installation:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_m/5_1v6z2d32q2kl1qkv39zzw80000gp/T/pip-build-zU8urF/jpype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/_m/5_1v6z2d32q2kl1qkv39zzw80000gp/T/pip-boim6J-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_m/5_1v6z2d32q2kl1qkv39zzw80000gp/T/pip-build-zU8urF/jpype1/

**Comment by marscher** [comment]
redo with -v flag to get some useful output, if you want help.
