### ISSUE TITLE
jpype JVM doesnt load SunJCE security providers

### ISSUE THREAD

**Issue by jbraun11** [originell/jpype#212]
trying to authorize via kerberos using sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType encryption type and experiencing the errror "Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/CBC/NoPadding".

when i check the loaded security providers, several security providers are present except for SunJCE. i can authorize via kerberos fine when running in java so it is not an environment issue.

any ideas on a fix or workaround?

**Comment by marscher** [comment]
Do you know if these providers are implemented using a "custom"/non-default classloader? I'm asking because jpype does not support custom class loaders. 

From the introduction found here https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html#Introduction, it seems like one should not explicitly specify the provider.

**Comment by jbraun11** [comment]
yeah, im not specifying the provider explicitly. kerberos is configured to use aes 256 which is provided by SunJCE. and no, it just uses the extensions class loader.

**Comment by marscher** [comment]
Do you have to use extensions class loader yourself or is it used internally within the library?

**Comment by jbraun11** [comment]
its used internally w/in the library

**Comment by jbraun11** [comment]
the security providers that are loaded properly are using a bootstrap class loader. any ideas on how to properly load security providers that use an extensions class loader?

**Comment by marscher** [comment]
On 03/21/2017 03:06 PM, jbraun11 wrote:
> the security providers that are loaded properly are using a bootstrap class loader. any ideas on how to properly load security providers that use an extensions
> class loader?

Outside of Java - no idea - sorry. Isn't there a public interface in JCE which wraps around the loading?

**Comment by jbraun11** [comment]
the issue is caused by configuration settings for my jvm. not an issue w/ jpype

**Comment by zhengyu88** [comment]
I encountered the same issue here, may I ask how to configure jvm settings for this? @jbraun11
