### ISSUE TITLE
jpype crashing on windows 7 

### ISSUE THREAD

**Issue by toofan0909** [originell/jpype#213]
Hello 

I am trying to get a simple java jar file working with my python program hence I am looking at jpype. At the moment I even unable to get a simple jvm started up with jpype.

here is simple python program that i am trying , please guide.

-------------------------- simple_test.py-------------------------------
import jpype
import os

print jpype.getDefaultJVMPath()
print jpype.isJVMStarted()

print "------------------------" 
jpype.startJVM(jpype.getDefaultJVMPath(),"-ea")
print jpype.isJVMStarted()

-------------------------- end of file ---------------------------------------

python -v

Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (
Intel)] on win32

Details of jvm and java file 

C:\>java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

C:\Program Files\Java\jre1.8.0_121\bin\server\jvm.dll

C:\>where java
C:\ProgramData\Oracle\Java\javapath\java.exe
C:\Program Files\Java\jre1.8.0_121\bin\java.exe 

Please guide

**Comment by marscher** [comment]
you're mixing 32bit python with 64 bit java. This can not work. The bitness of both programs has to be the same.
