### ISSUE TITLE
No overloads found for jpype.java.time.Instant.parse

### ISSUE THREAD

**Issue by nimish** [originell/jpype#219]
import jpype
     jpype.java.time.Instant.parse('123') # no matching overload
     jpype.java.time.Instant.parse.matchReport() # shows the 1 overload 

JavaDocs [here](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#parse-java.lang.CharSequence-)

Really irritating as there doesn't look to be a good workaround.

**Comment by nimish** [comment]
(Assumes you started the JVM and the like)

**Comment by marscher** [comment]
wrap your string in a java.lang.String

**Comment by nimish** [comment]
mind blown

**Comment by nimish** [comment]
Can this not be automated by JPype in whatever JClass's __call__ is?
