### ISSUE TITLE
Class not found on OS X El Capitan

### ISSUE THREAD

**Issue by liangzhen-pku** [originell/jpype#222]
Whenever I want to use `jpype.JClass()` to import a class, I constantly get the following message:

```
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class TestApi not found
```
I'm using Java 1.6 and Python 2.7. Anyone has the same problem on a Mac?

**Comment by marscher** [comment]
double check your classpath argument you've passed to the jvm. This has most likely nothing to do with the underlying operating system (osx, etc.). And please avoid double posting (copy paste issues) the same thing twice in the future, you are wasting other people time by doing so...
To clarify: JClass and JPackage are very related to each other. Perhaps you should read some literature.
