### ISSUE TITLE
Package xxxx is not callable on OS X El Capitan

### ISSUE THREAD

**Issue by liangzhen-pku** [originell/jpype#223]
Whenever I use `jpype.JPackage()` to import a class and create a new object, for example,

```
DelegateHandler = JPackage("jpype.xml").DelegateHandler
dh = DelegateHandler(None, None, JProxy("org.xml.sax.ContentHandler", inst=ContentHandler()), None)
```
I constantly get the error message `TypeError: Package xxxx is not Callable`.

I'm using Java 1.6 and Python 2.7. Anyone has the same problem on a Mac?

**Comment by marscher** [comment]
a package and class are not the same thing. Are you familiar with Java?
