### ISSUE TITLE
Segmentation fault (core dumped) when use startJVM

### ISSUE THREAD

**Issue by DongjunLee** [originell/jpype#243]
Enviroment
- Ubunto 16.04
- Python 3.6
- JPype1 (0.6.2)
- Java - openjdk version "1.8.0_131"

There is some error in startJVM.
I don't know what is the problem. need advice

```python
>>> import jpype
>>> jpype.startJVM(jpype.getDefaultJVMPath())
Segmentation fault (core dumped)
```

**Comment by atulkhairnar** [comment]
Enviroment

    Ubunto 16.04
    Python 3.5.2
    JPype1 (0.6.2)
    Java - openjdk version "1.8.0_131"

There is some error in startJVM.
I don't know what is the problem. need advice

```
>>> import jpype
>>> jpype.startJVM(jpype.getDefaultJVMPath())
Segmentation fault (core dumped)
```

**Comment by Thrameos** [comment]
Ubunto is currently shipping a broken Kernel that does not support a JVM.   This is a  known issue.  They should be shipping a revised kernel soon.  

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1699772
