### ISSUE TITLE
High memory usage / memory leak

### ISSUE THREAD

**Issue by robbert-ef** [originell/jpype#245]
We use JPype to integrate Aspose PDF / Aspose Words for Java in which PDF documents can be manipulated using Java. This results in a huge amount of memory used when for example a document is saved to disk.
In our case the Python process takes up 500MB+ while JVM is set to use 256MB using `-Xms256m` and `Xmx256m` flags. Data transferred between our Python process and Java JVM is limited to only some simple strings such as filenames, all processing logic is done in Java.
When saving multiple documents, the memory used keeps increasing.
What could be the cause of this memory usage? Is this a bug?

While investigating this issue I noticed a possible memory leak in JPype 0.6.2, see the following example in which a `java.lang.String` object is created numerous times:

```python
# -*- coding: utf-8 -*-
import jpype
import gc
import sys
import resource

try:
    xrange
except NameError:
    xrange = range

def memory_usage_resource():
    # The Python docs aren't clear on what the units are exactly, but
    # the Mac OS X man page for `getrusage(2)` describes the units as bytes.
    # The Linux man page isn't clear, but it seems to be equivalent to
    # the information from `/proc/self/status`, which is in kilobytes.
    if sys.platform == 'darwin':
        rusage_mp = 1
    else:
        rusage_mp = 1024
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss * rusage_mp

jpype.startJVM(jpype.getDefaultJVMPath(), "-Xms64m", "-Xmx64m")

runtime = jpype.java.lang.Runtime.getRuntime()

for i in xrange(100000000):
    # Create a java.lang.String
    jpype.java.lang.String('a')
    if i % 10000 == 0:
        jpype.java.lang.Runtime.getRuntime().gc()
        gc.collect()
        rss_memory = memory_usage_resource()

        jvm_total_mem = runtime.totalMemory()
        jvm_free_mem = runtime.freeMemory()
        num_gc_objects = len(gc.get_objects())

        print("%d: RSS %d Mb, JVM (total %d Mb, free %d Mb), num gc objects: %d" % (
            i,
            (rss_memory / 1024 ** 2),
            (jvm_total_mem / 1024 ** 2),
            (jvm_free_mem / 1024 ** 2),
            num_gc_objects
            ))
```

Results in the following output using JPype 0.6.2

> 3000000: RSS 156 Mb, JVM (total 61 Mb, free 61 Mb), num gc objects: 8118
> 3010000: RSS 156 Mb, JVM (total 61 Mb, free 61 Mb), num gc objects: 8118
> 3020000: RSS 156 Mb, JVM (total 61 Mb, free 61 Mb), num gc objects: 8118

When using JPype 0.6.1, memory usage stays stable:

> 3000000: RSS 46 Mb, JVM (total 61 Mb, free 61 Mb), num gc objects: 8087
> 3010000: RSS 46 Mb, JVM (total 61 Mb, free 61 Mb), num gc objects: 8087
> 3020000: RSS 46 Mb, JVM (total 61 Mb, free 61 Mb), num gc objects: 8087

**Comment by marscher** [comment]
thanks for your report and the working example. I'm investigating this now. We should add a valgrind test to the suite.

**Comment by marscher** [comment]
jp_class.cpp:133 new JPMethod is not cleared.

**Comment by marscher** [comment]
same for ctors

**Comment by marscher** [comment]
since this code is fairly old (2012) it seems like loadMethods is called more often than it should.

**Comment by marscher** [comment]
these jp_class related errors were induced by not calling jpype.shutdownJVM(). However it seems like the passed string is never garbage collected (on JVMs side), so there is some kind of refcounting weirdness going on.

**Comment by Thrameos** [comment]
Hopefully not something I introduced.  Was the leak recent?

**Comment by marscher** [comment]
On 07/20/2017 03:21 PM, Karl Nelson wrote:
> Hopefully not something I introduced. Was the leak recent?
I have not tested this. If we could make a test, which really fails
(exit code != 0 for a detected leak), we could do a git bisect script ...

**Comment by Thrameos** [comment]
Okay it appears that I was at least partially responsible for this the leak.   The key issue is that reference counting of classes and objects is being handled by convention.  That is one needs to create a cleaner for all references generated as part of a number of accessors.  However, this is true for some and not all.  Further, there are a number of cases in the code where a global reference is produced in the accessor and then the cleaner is told that it is a local reference.  The code that I added for the argument types copied one of the patterns that was bad and thus moved the leak onto the invoke method path which is critical.   I will submit a patch that moves cleaner from by convention to required.  All accessors that produce a new reference will need to take a JPCleaner&.  They will then add the appropriate reference type to the cleaner.  This will eliminate the chance that a cleaner is not used and ensure that the right type of reference is cleaned.

**Comment by marscher** [comment]
@robbert-ef Can you please try the recent master branch and report back, if the leak has been fixed?

**Comment by Thrameos** [comment]
Isn't this leak tester now part of our test system in leak.py?  It should be "testStringLeak".  We can add more as needed.

**Comment by marscher** [comment]
you're right.
