### ISSUE TITLE
PyPy

### ISSUE THREAD

**Issue by Thrameos** [originell/jpype#249]
I investigated why Jpype was not running with PyPy.  It appears that there are some errors with reference counting in the pythonenv.  The JPySequence wrapper does not appear to add any value over the standard CPython interface and it is adding a lot of extra steps including calls to determine what type of object is being worked on.  These calls when operating on an object under initialization are causing the NULL pointer which makes PyPy abort.  I would strongly recommend removing much of the pythonenv wrappers. They add unnecessary steps and are not providing any useful abstraction over the standard CPython interface.  If we do plan to keep them they need to be broken into proper types rather than polymorphic types like JPySequence.  I will clean up those that are problematic and submit a patch.

**Comment by marscher** [comment]
I think the best solution would be to remove pythonenv completely and replace it with pybind11. It supports pypy out of the box. This would involve binding the model classes in native/common. However this seems to be lots of work.

**Comment by Thrameos** [comment]
This has been completed in #334   

The key problem was that PyPy does not support  certain checking between types while tuples are being constructed.  Thus the abstraction that was filling generated a seg fault.  The tests are still failing regarding memory because PyPy does not use the same aggressive deallocation scheme as CPython.  We would need to rework the tests to account for this.  But for now the code is working even if we have some false tests.
