### ISSUE TITLE
how to set the log level?

### ISSUE THREAD

**Issue by IvyGongoogle** [originell/jpype#259]
hello, when I use the follow code:

```
    jarpath="./HanLP_Demo.jar" 
    jpype.startJVM(jpype.getDefaultJVMPath(), "-Djava.class.path=%s" %(jarpath))
    Demo = jpype.JClass('HanLP_Demo.Demo')
    demo=Demo()
```
the shell output still contains string:
```
JVM activity report     :
	classes loaded       : 29
JVM has been shutdown
```
how should get rid of this string? can you give some advises?

**Comment by IvyGongoogle** [comment]
@marsam when to relax the latest version of jpype that can disable jvm activity report?

**Comment by marscher** [comment]
@Thrameos what do you think, when should we schedule are release?

**Comment by Thrameos** [comment]
I think that we definitely need a release.  The only question is should the leak fix and the multithreaded patches go in before the release.   I would generally think that we shouldn't release anything with a known leak.  I won't have much development cycles free until after the end of the government fiscal year.  But if there is anything required to help get the release out I will try to get it done.

**Comment by IvyGongoogle** [comment]
@marscher Nothing. I can use your [fix](https://github.com/originell/jpype/issues/260)  by `python setup.py`.

**Comment by IvyGongoogle** [comment]
@marscher  when to release the new version which can set the log level?

**Comment by IvyGongoogle** [comment]
@Thrameos  I am looking for a version which can set the log level to simple solve my issue 61 that I proposed

**Comment by Thrameos** [comment]
I thought that 0.6.3 had the patch to disable the logging.  I don't currently have a patch to make it switchable.

I do not understand "can set the log level to simple".  Please elaborate.

**Comment by IvyGongoogle** [comment]
@Thrameos  I mean that whether 0.6.3 can set the log level that get rid of string like:
`
JVM activity report     :
	classes loaded       : 29
JVM has been shutdown
`

**Comment by Thrameos** [comment]
I have not seen that line in the output of 0.6.3 that I have loaded on my machine.

hello.py:
```
import jpype
import jpype.imports
jpype.startJVM(jpype.getDefaultJVMPath())
import java.lang.String

print(java.lang.String("hello world"))
```

Test:
```
$ python3 hello.py
hello world

$
```
Nothing printed but the "hello world".  So at least the version in git has those statistics disabled.  I think the patch went before the release, but you would need to verify that.

**Comment by ozturkberkay** [comment]
@Thrameos I'm using JPype1 0.6.3, installed using: `pip install JPype1`. My code also prints out logs. For example:

**Code:**
```java
jp.startJVM(jp.getDefaultJVMPath(), "-ea", "-Djava.class.path=%s" % (JAR_PATH))
jp.shutdownJVM()
```

**Console:**
```console
JVM has been shutdown
```

 Is there a way to disable this without recompiling the source code?
