### ISSUE TITLE
[Error] ImportError: ***/anaconda3/lib/python3.5/site-packages/JPype1-0.6.2-py3.5-linux-x86_64.egg/_jpype.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by TimKrowder** [originell/jpype#266]
linuxmint 18
anaconda3/python3.5
sun-jdk-1.8.0
code
```
import jpype as jpy
jvmPath = jpy.get_default_jvm_path()
jpy.startJVM(jvmPath)
jpy.java.lang.System.out.println("hello")
```

**Comment by marscher** [comment]
I guess you are using jpype1 from conda-forge then? Can you please try installing libgcc to solve the problem?

**Comment by TimKrowder** [comment]
I reinstall anaconda3(python3.6),and reselect a mirror , then it worked. You say  "using jpype1 from conda-forge" is right. Thank you!
