### ISSUE TITLE
Document startJVM correctly

### ISSUE THREAD

**Issue by spookylukey** [originell/jpype#267]
(Changed first comments in which I couldn't find documentation for startJVM).

`startJVM` is described early on in docs. It would be nice if this linked to the API docs, especially as search feature on readthedocs is quite poor in this regard. The API docs are also incorrect - as they describe `startupJVM` not `startJVM`, which means searching for the docs doesn't find you anything, and I thought this method was undocumented.

**Comment by spookylukey** [comment]
Looks like there are quite a few places where `startupJVM` is mentioned, they all need fixing.

**Comment by marscher** [comment]
happy to accept a PR for this.
