### ISSUE TITLE
Why jvmfinder looks for 'libjvm.so'?

### ISSUE THREAD

**Issue by KWJG** [originell/jpype#273]
https://github.com/originell/jpype/blob/8d479b959fe75054181f93b4c2bdb4ca3f65518c/jpype/_jvmfinder.py#L37

I have JRE installed, set the JAVA_HOME environmental parameter to that directory.

I found that the _jvmfinder is not finding the jvm.dll properly, because

my C:\Program Files (x86)\Java\jre1.8.0_151\bin\client

folder has jvm.dll, but not libjvm.so.

(I had to make a dummy file 'libjvm.so' in that directory. Then it went well.)

**Comment by marscher** [comment]
On 08.12.2017 12:58, KWJG wrote:
> https://github.com/originell/jpype/blob/8d479b959fe75054181f93b4c2bdb4ca3f65518c/jpype/_jvmfinder.py#L37
> 
> I have JRE installed, set the JAVA_HOME environmental parameter to that directory.
> 
> I found that the _jvmfinder is not finding the jvm.dll properly, because
> 
> my C:\Program Files (x86)\Java\jre1.8.0_151\bin\client
> 
> folder has jvm.dll, but not libjvm.so.
> 
> (I had to make a dummy file 'libjvm.so' in that directory. Then it went well.)
> 
> 

I assume you are using a wonderful Microsoft product? We only use this 
finder class in Linux environments. So your product is fooling Python to 
think it is Linux. Please enlighten us :)

**Comment by KWJG** [comment]
I found the correct code from ._windows . Thank you for fast response.
