### ISSUE TITLE
Segfault when constructing types before startJVM

### ISSUE THREAD

**Issue by jaseg** [originell/jpype#275]
It would probably be good if the c++ backend would briefly check whether Java has in fact been initialized and print a useful error message instead of just crashing the process when accessing stuff before doing ```startJVM```.

Example code triggering this:
```python
import jpype
jpype.JString('a')
```

**Comment by Thrameos** [comment]
I tested with the master and got this...

```$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    jpype.JString('a')
  File "C:\ProgramData\Miniconda3\lib\site-packages\jpype1-0.6.2-py3.6-win-amd64.egg\jpype\_jwrapper.py", line 36, in __init__
    self._value = _jpype.convertToJValue(self.typeName, v)
RuntimeError: Java Subsystem not started
```

**Comment by marscher** [comment]
The propagated exception leads to an seg fault? Thats pretty bad. Or does Python just die happily with the shown RuntimeError?

**Comment by Thrameos** [comment]
It dies happily when I tested it.  But the user had reported this as crash.  So either it is a version difference or an architecture difference.  

I believe this was in the segfault clean up patch.  Previously creating an object would try to access a resource which was not pushed into the _jpype C++ module until the jvm was started.  If others get the crash on the latest then I will need to dig deeper.

**Comment by Thrameos** [comment]
Testing of the issue on master.

```python
import jpype
try:
    jpype.JString('a')
except RuntimeError:
    print("Not dead yet!")
```

gives

```
$ python3 test.py
Not dead yet!
```

**Comment by marscher** [comment]
thanks for testing, seems to be fixed on master.
