### ISSUE TITLE
Poor integration of numpy

### ISSUE THREAD

**Issue by Thrameos** [originell/jpype#294]
One issue that I am running into is the tendency for np.array() to return a single element as a numpy type.

```
a=np.array([1,2,3])
type(a[0])
>  numpy.float64
```

Some interfaces take this an convert properly while others produce unable to find matching overload or unable to convert.  I haven't mapped out all of the interfaces that have this issue, but I am finding that I need to wrap a lot of calls with explicit conversions, ie.  `foo(float(a[0]))`  which seems unnecessary.  As an enhancement we should place the appropriate conversions between all of the different types in numpy when numpy was compiled into the jpype module.  This would reduce the number of explicit casts and simplify the interface.

**Comment by marscher** [comment]
I like your suggestion to fix this, please go ahead.

**Comment by Thrameos** [comment]
Completed as branch for #334
