### ISSUE TITLE
Implement convenient import

### ISSUE THREAD

**Issue by KOLANICH** [originell/jpype#295]
There is a mechanism in python interpreter allowing hooking into import. It will allow us to have convenient imports in jython style.
The example of implementation of a custom importer: https://github.com/KOLANICH/NTMDTRead/blob/master/NTMDTRead/palettes/__init__.py#L59

**Comment by Thrameos** [comment]
Isn't that what is in `jpype.imports`?  Unfortunately, it only works for python3, but we have implemented the pattern for `import java.lang.String`, `from java.lang import String` and `from java.lang import String as mystr`.  Wildcards are not currently supported.

**Comment by KOLANICH** [comment]
Oh, it is, thank you. We should really update the docs on ReadTheDocs

**Comment by Thrameos** [comment]
Not sure how ReadTheDocs gets populated.  On the other hand, the docs are current for 0.6.2.  We are behind on cutting a new release.

**Comment by originell** [comment]
@KOLANICH @Thrameos I configured our readthedocs. It's pretty straightforward. They build on every new push/release by looking for a `conf.py` (as we are using sphinx to build the docs). 

If you guys have any other needs, just highlight me :)

**Comment by KOLANICH** [comment]
@originell, thank you.
