### ISSUE TITLE
int to float convertion produced 0.

### ISSUE THREAD

**Issue by Thrameos** [originell/jpype#296]
Normally I used doubles for all interfaces that are taking a float value from python, but recently I was porting code that had to use a explicit float.  In one of the conversions I ended up with a 0 value where an integer was passed into a float.  It appears that one of the conversion routines missed a case and gave `canConvert` but did not actually perform the conversion.  It wasn't caught in testing so appears we have an incomplete testing of this section.  

This may be a recent issue.  I will investigate when I can.

**Comment by Thrameos** [comment]
See pull request #300.

**Comment by Thrameos** [comment]
Resolved.

**Comment by seilhan3** [comment]
It appears to still be broken on 0.6.3 when I call a function that accepted a float.
