### ISSUE TITLE
Impossible to call methods on JavaClass

### ISSUE THREAD

**Issue by KOLANICH** [originell/jpype#305]
For now it's impossible to call methods on a `JavaClass` because it is implemented in C++ and doesn't proxies methods. It spoils all the reflection, especially if I have to `getClassLoader()`, `getDeclaredAnnotationsByType()` and `getDeclaredAnnotations()`. Required for #297 for Scala signatures.

**Comment by Thrameos** [comment]
Can you give an example of what you are trying to call?  I have called methods directly on the class using get declared method.  It should be possible since varargs was added.

**Comment by KOLANICH** [comment]
>It should be possible since varargs was added.

I use the release from conda with some new features implemented in python backported (have copied imports.py and _jcore.py from master). The release is dated to
>26 days and 15 hours ago

but it is unclear if it contains these commits or if it was built from the v0.6.2 tag.

I tried doing the methods mentioned on class directly and on ```__javaclass__```, there is no such methods there.

**Comment by Thrameos** [comment]
There was a large rework a while back that added `class_` which supports all the reflection api.  But as far as I know it isn't in any conda build. I needed it to get to annotations.  The backport is unlikely to cut it as it took a rework of the C++ matching algorithm to get varargs.

We are way behind on cutting a release. We should have cut one after the last rework, but a set of minor bugs never got worked out entirely.  We could cut another release now. But I am currently in a massive rework to upgrade to java 8 lambdas.  Thus we either have a 0.6.3 or wait til 0.7.0 is ready.

**Comment by KOLANICH** [comment]
Conda build has been upgraded, but I still cannot call `getDeclaredAnnotations`. Could you make an example how to call this right?

**Comment by Thrameos** [comment]
Try the following code

```
import java.security.Certificate
[str(i) for i in java.security.Certificate.class_.getDeclaredAnnotations()]
```

Should give you `['@java.lang.Deprecated()']`

Please note that annotations are only available if they have been declared as runtime policy (`@Retention(RetentionPolicy.RUNTIME)`)

**Comment by KOLANICH** [comment]
Thank you, that works!
