### ISSUE TITLE
Need a release candidate for 0.6.3

### ISSUE THREAD

**Issue by Thrameos** [originell/jpype#306]
We need to close a stable version for the 0.6 branch.  I am most of the way through a 0.7 codewise, but it may be a while before it is near bug free.  It may be a good idea to get stable version with the current feature set before we cut into serious development.

**Comment by marscher** [comment]
So you consider master stable enough for a release?

**Comment by marscher** [comment]
bumped 0.6.3

**Comment by Thrameos** [comment]
I have been running a group of 8 people with master for the last year.  We beat on it with scientific computing sized runs most days of the week.  However, I can't say that we hit too deeply into the system.   JProxy and memory view are definitely not on our code path check.   Unfortunately, some people work around problems rather than report so the float one escaped my attention for a while.

The list of known issues for me:
1) JProxy has a bad pattern that is bound to either leak or delete an object while in use.  #276
2) Unicode translation is incorrect in both python 2 and 3 because java uses UTF-16 encoded UTF-8 resulting in problems for anything above 16 bit unicode. #278
3) Lambdas #274 

That is a pretty light set of issues.  

Beyond the issues, most people in my group are running smoothly.  There is a generally difficulty getting started with java path issues.  Only one person in my group managed to get master running and set up the Java path to get the jars.  This isn't really a problem with jpype but the whole design of java.  It doesn't tell you when it isn't using a jar thus if even one jar in the dependency list is missing the new user gets a cryptic error about the class not found.  jpype.imports helped a bit, checking for architecture helped more.  Not likely to ever be resolved.
