### ISSUE TITLE
Installation error with amazon linux

### ISSUE THREAD

**Issue by sathik11** [originell/jpype#311]
Python version - Python 3.5
Operating System - Amazon Linux AMI

Tried to install jpype1==0.6.2 on AWS ec2 instance . But returns with error shown below
I have the gcc c++(gcc48.x86_64 ) installed on aws . Same error appears for latest version of JPype1(0.6.3)

I have also added the symlink for cc1plus (/usr/libexec/gcc/x86_64-amazon-linux/4.8.5)  to /usr/local/bin 
But that didnt help.

I have earlier installed it on another AWS instance without any issues 

` Running setup.py bdist_wheel for JPype1 ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-keuik2a3/JPype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-_ukrhgl6 --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/jpype
  copying jpype/_jpackage.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_pykeywords.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_windows.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_jexception.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_linux.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_properties.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_core.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_jwrapper.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_jcollection.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/nio.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_jvmfinder.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_jobject.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_jclass.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_gui.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_darwin.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_jarray.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/__init__.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_jproxy.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/reflect.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/JClassUtil.py -> build/lib.linux-x86_64-3.5/jpype
  copying jpype/_refdaemon.py -> build/lib.linux-x86_64-3.5/jpype
  creating build/lib.linux-x86_64-3.5/jpype/awt
  copying jpype/awt/__init__.py -> build/lib.linux-x86_64-3.5/jpype/awt
  creating build/lib.linux-x86_64-3.5/jpype/awt/event
  copying jpype/awt/event/WindowAdapter.py -> build/lib.linux-x86_64-3.5/jpype/awt/event
  copying jpype/awt/event/__init__.py -> build/lib.linux-x86_64-3.5/jpype/awt/event
  creating build/lib.linux-x86_64-3.5/jpypex
  copying jpypex/__init__.py -> build/lib.linux-x86_64-3.5/jpypex
  creating build/lib.linux-x86_64-3.5/jpypex/swing
  copying jpypex/swing/pyutils.py -> build/lib.linux-x86_64-3.5/jpypex/swing
  copying jpypex/swing/__init__.py -> build/lib.linux-x86_64-3.5/jpypex/swing
  copying jpypex/swing/AbstractAction.py -> build/lib.linux-x86_64-3.5/jpypex/swing
  running build_ext
  /tmp/pip-install-keuik2a3/JPype1/setup.py:164: FeatureNotice: Turned ON Numpy support for fast Java array access
    FeatureNotice)
  building '_jpype' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/native
  creating build/temp.linux-x86_64-3.5/native/common
  creating build/temp.linux-x86_64-3.5/native/python
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_NUMPY=1 -Inative/common/include -Inative/python/include -Inative/jni_include -I/usr/local/lib64/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c native/common/jp_class.cpp -o build/temp.linux-x86_64-3.5/native/common/jp_class.o -ggdb
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for JPype1
  Running setup.py clean for JPype1
Failed to build JPype1
Installing collected packages: JPype1
  Running setup.py install for JPype1 ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-keuik2a3/JPype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ypvnz9yy/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/jpype
    copying jpype/_jpackage.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_pykeywords.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_windows.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_jexception.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_linux.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_properties.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_core.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_jwrapper.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_jcollection.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/nio.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_jvmfinder.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_jobject.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_jclass.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_gui.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_darwin.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_jarray.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/__init__.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_jproxy.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/reflect.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/JClassUtil.py -> build/lib.linux-x86_64-3.5/jpype
    copying jpype/_refdaemon.py -> build/lib.linux-x86_64-3.5/jpype
    creating build/lib.linux-x86_64-3.5/jpype/awt
    copying jpype/awt/__init__.py -> build/lib.linux-x86_64-3.5/jpype/awt
    creating build/lib.linux-x86_64-3.5/jpype/awt/event
    copying jpype/awt/event/WindowAdapter.py -> build/lib.linux-x86_64-3.5/jpype/awt/event
    copying jpype/awt/event/__init__.py -> build/lib.linux-x86_64-3.5/jpype/awt/event
    creating build/lib.linux-x86_64-3.5/jpypex
    copying jpypex/__init__.py -> build/lib.linux-x86_64-3.5/jpypex
    creating build/lib.linux-x86_64-3.5/jpypex/swing
    copying jpypex/swing/pyutils.py -> build/lib.linux-x86_64-3.5/jpypex/swing
    copying jpypex/swing/__init__.py -> build/lib.linux-x86_64-3.5/jpypex/swing
    copying jpypex/swing/AbstractAction.py -> build/lib.linux-x86_64-3.5/jpypex/swing
    running build_ext
    /tmp/pip-install-keuik2a3/JPype1/setup.py:164: FeatureNotice: Turned ON Numpy support for fast Java array access
      FeatureNotice)
    building '_jpype' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/native
    creating build/temp.linux-x86_64-3.5/native/common
    creating build/temp.linux-x86_64-3.5/native/python
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_NUMPY=1 -Inative/common/include -Inative/python/include -Inative/jni_include -I/usr/local/lib64/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c native/common/jp_class.cpp -o build/temp.linux-x86_64-3.5/native/common/jp_class.o -ggdb
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-keuik2a3/JPype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ypvnz9yy/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-keuik2a3/JPype1/
`

**Comment by marscher** [comment]
your system is clearly lacking a functional c++ compiler. This has nothing to do with jpype it self. Please read your "distros" manual on how to install the compiler properly.

**Comment by sathik11** [comment]
For others using AMI   
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11) version compiles Jpype

whereas  newer version gcc72-c++.x86_64 doesnt compile

**Comment by marscher** [comment]
On 23.04.2018 08:45, Sathik wrote:
> For others using AMI
> gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11) version compiles Jpype
> 
> whereas  newer version gcc72-c++.x86_64 doesnt compile
> 
It is not even invoked properly, the output says that it can not find 
the compiler program. JPypes code does compile with gcc7

**Comment by Thrameos** [comment]
@sathik11 To be clear the  gcc72-c++.x86_64 appears to be improperly installed on your system.  It is possible that it has to do with the compiler flags that python is applying triggering the bad install, but the fundamental problem is on your system.  My best guess is that gcc7.2 is installed on your system but a portion of the g++7.2 is not (or is the wrong installation version, installation location, or wrong architecture).  Either way the "spec" file for your gcc was compiled with doesn't point to the correct C++ version thus the error.  

```
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
```

'cc1plus' is the backend for g++.  The error message is simply stating the compiler is not able to find a vital piece.  Our recommendation that you check the distribution and find out what package is not properly installed.  The error has nothing to do with Jpype other that Jpype happened to be the program that you tried to compile with the broken compiler.

**Comment by sathik11** [comment]
Thanks @marscher @Thrameos  ..
Apologise for posting this as a Jpype issue . It was my lack of knowledge on c++ compiler.. 
I was able to run with gcc 4.8.5

**Comment by allansene** [comment]
This one solved for me:

`sudo yum install redhat-rpm-config gcc-c++ python3-devel unixODBC-devel`
