### ISSUE TITLE
How to solve the parameter return in jpype?

### ISSUE THREAD

**Issue by 5368** [originell/jpype#314]
How to solve the parameter return in jpype?
> Java function is brought back to the function through the incoming parameters
Example:

> [java:]
>byte [] out = new byte[cText.length];
>byte [] aKey = T2.Ascii2Text(cKey).getBytes("utf-8");
>int ret = T2.CFB0(cText, cText.length, out, 1, aKey);		
>System.out.println("m:"+new String(out));

>[python3:]
>ff=jpype.JPackage("com.xx.crypto.utils").TemplateTripleDesCryptVarKey
>ff.T2.CFB0(kk,len(kk),f0,1,key)

**Comment by Thrameos** [comment]
If you must allocate an array to return to in java then you do the same in python.  Use JArray to create an array to act as the return buffer.

Python:
```
out=jpype.JArray(jpype.JByte,1)(len(kk)) # <-- calls "new byte[len]"
ff=jpype.JPackage("com.xx.crypto.utils").TemplateTripleDesCryptVarKey
ff.T2.CFB0(kk,len(kk),out,1,key)
print("m:"+out[:])
```

**Comment by 5368** [comment]
I am very grateful to you for your advice
