### ISSUE TITLE
Binary packages for Mac

### ISSUE THREAD

**Issue by marscher** [originell/jpype#62]
Hi,
just want to ask if somebody of our maintainers can provide binary packages (maybe wheel format?) for MacOSX to avoid need for a JDK?

Best,
Martin

**Comment by marscher** [comment]
they are now available for Anaconda as binaries on binstar:
https://binstar.org/omnia/jpype1

**Comment by originell** [comment]
woop woop! :dancer: :dancers:

**Comment by baztian** [comment]
I'm not a mac user. Would it be useful/possible to also provide binary packages for mac users on pypi? Are there any icons/badges similar to travis and appveyor to show we are providing Anaconda packages. Would it be useful/possible to integrate binstar automatic builds into pull requests?
