### ISSUE TITLE
testProxyWithArguments fails for  Python > 2.7.3

### ISSUE THREAD

**Issue by marscher** [originell/jpype#67]
We didn't notice that, because travis currently uses 2.7.3. But this will be updated soon. It seems it happens somewhere in finalization code. Thats the stacktrace in current Python:

    #0  0x00007ffff6f06f79 in raise () from /lib/x86_64-linux-gnu/libc.so.6
    #1  0x00007ffff6f0a388 in abort () from /lib/x86_64-linux-gnu/libc.so.6
    #2  0x0000000000557f5f in Py_FatalError ()
    #3  0x00000000005537f7 in PyThreadState_Get ()
    #4  0x00000000004b108b in subtype_dealloc ()
    #5  0x000000000048dc57 in _Py_Dealloc ()
    #6  0x00007ffff65684b2 in PythonHostEnvironment::releaseRef(void*) () at src/native/python/py_hostenv.cpp:33
    #7  0x00007ffff653072f in HostRef::~HostRef() () at src/native/common/jp_env.cpp:332
    #8  0x00007ffff653075e in HostRef::~HostRef() () at src/native/common/jp_env.cpp:333
    #9  0x00007ffff65307ea in HostRef::release() () at src/native/common/jp_env.cpp:342
    #10 0x00007ffff652ffbe in JPCleaner::~JPCleaner() () at src/native/common/jp_env.cpp:209
    #11 0x00007ffff6548532 in Java_jpype_JPypeInvocationHandler_hostInvoke(JNIEnv_*, _jclass*, _jstring*, long, _jobjectArray*, _jobjectArray*, _jclass*) () at src/native/common/jp_proxy.cpp:138

**Comment by baztian** [comment]
This test doesn't fail on python 3 using the tcalmant port (that's why I've changed the skip condition of this test)

**Comment by baztian** [comment]
As this now also fails on python 3 it might be a good start to check the difference between originell's code and tcalmant's code.

**Comment by kutschkem** [comment]
Hi, could it be this issue that tcalmant fixed in his code?
https://github.com/tcalmant/jpype-py3/issues/1

**Comment by baztian** [comment]
@kutschkem thank you very much for pointing to the fix! That seems to fix it.
