### ISSUE TITLE
Unable to start JVM

### ISSUE THREAD

**Issue by keithsun80** [originell/jpype#84]
I push the code to the test enviroment , and there are another Exception.... T . T

The project in my enviroment there are no problem.

Exception in below.

```
Traceback (most recent call last):
  File "/home/prod/softwares/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/prod/deploys/WiwideOP/libs/rsa/api/rsa_adapter.py", line 63, in wrapper
    result = rsa_api.auth(user_name, pass_code)
  File "/home/prod/deploys/WiwideOP/libs/rsa/api/rsa_api.py", line 26, in auth
    startJVM(getDefaultJVMPath(), "-Djava.class.path=%s" % CLASS_PATH)
  File "build/bdist.linux-x86_64/egg/jpype/_core.py", line 44, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unable to start JVM at src/native/common/jp_env.cpp:71
```

java version "1.6.0_32"
OpenJDK Runtime Environment (IcedTea6 1.13.4) (6b32-1.13.4-4ubuntu0.12.04.2)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

We use uwsgi to start project , is that problem?

**Comment by rapgro** [comment]
The discussion here leads me to a more general question. Is JPype designed and able to execute multiple threads? Are those threads executed in the same JVM instance or in several processes individually? I've seen strange issues with Java when there are two JVM instances running in parallel.

**Comment by baztian** [comment]
JPype is able to execute Java code from multiple Python threads or multiple Java threads. In the first case make sure you call attachThreadToJVM and detachThreadToJVM in the corresponding Python threads. JPype only allows one JVM instance during one Python interpreter session.

**Comment by StevenLOL** [comment]
same error, to reproduce:
'''
startJVM(getDefaultJVMPath(), "-ea")
shutdownJVM()
startJVM(getDefaultJVMPath(), "-ea")
shutdownJVM()
'''
Java 7 Oracle, UBUNTU 15.04 64bits , python 2.7

**Comment by marscher** [comment]
@StevenLOL according to the fine documentation, "restarts" are not supported by the JVM.

**Comment by StevenLOL** [comment]
@marscher , thanks!

**Comment by Harshanah** [comment]
I got around this problem by creating a shell script . When program finished JVM can be shutdown . then parameters are passed from the shell script 
EX
#!/bin/bash
for  (( i=5; i<=21; i++ ))
do
k=0;
python use.py $i# i is passed as a system argument to python
echo "Finished $i"
done
