### ISSUE TITLE
appveyor support

### ISSUE THREAD

**Issue by marscher** [originell/jpype#96]
I do not have the permission to add the appveyor hooks for pullrequests etc. Kindly asking you @originell to add them :+1:

**Comment by originell** [comment]
oops completely overlooked this. do you still want them? ^^

**Comment by baztian** [comment]
I guess this is still really usefull to have the feedback if a pull request breaks something on windows. Don't know about the current state of the app veyor scripts though.

**Comment by marscher** [comment]
Am 07.03.2015 um 07:59 schrieb baztian:
> I guess this is still really usefull to have the feedback if a pull
> request breaks something on windows. Don't know about the current state
> of the app veyor scripts though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/originell/jpype/issues/96#issuecomment-77677060>.
>
its easy to achieve, I've got a template for this. But some repo owner 
has to enable it on appveyor.

**Comment by originell** [comment]
like this :)?

![image](https://cloud.githubusercontent.com/assets/23529/6546201/4b70fe02-c5ab-11e4-9987-86aebaa5f998.png)

**Comment by marscher** [comment]
Am 08.03.2015 um 15:53 schrieb Luis Nell:
> like this :)?
>
> image
> <https://cloud.githubusercontent.com/assets/23529/6546201/4b70fe02-c5ab-11e4-9987-86aebaa5f998.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/originell/jpype/issues/96#issuecomment-77753332>.
>
looks good, will try it out.

**Comment by baztian** [comment]
It seems that this issue can be closed as #129 has proven it works!?

**Comment by marscher** [comment]
yes, thank you!

**Comment by marscher** [comment]
@originell Can you please add me as an admin user to the Appveyor project so I can take care about things?

**Comment by originell** [comment]
@marscher sure! I just can't find your github email. Could you mail me that?
